Repository kirbydesign/designsystem, pull requests merged in 2022-11, with the labels that each got.

#2577 Automate release notes and publishing
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
  .github/workflows/publish.yml
  apps/cookbook/src/app/page/header/header.component.ts
Labels: ignore-for-release

#2611 Allow empty constructors in eslint
  eslintrc-custom-overrides.json
Labels: ignore-for-release

#2607 Add ESlint to the flows app
  apps/flows/.eslintrc.json
  apps/flows/src/app/app.module.ts
  apps/flows/src/app/transaction-details-flow/account/account.component.ts
  apps/flows/src/app/transaction-details-flow/transaction-details-flow.component.ts
  apps/flows/src/app/transfer-and-pay-flow/choose-receiver/choose-receiver.component.ts
  apps/flows/src/app/transfer-and-pay-flow/details/details.component.ts
  apps/flows/src/app/transfer-and-pay-flow/other-page/other-page.component.ts
  apps/flows/src/app/transfer-and-pay-flow/other.service.ts
  apps/flows/src/app/transfer-and-pay-flow/own-account-page/own-account-page.component.ts
  apps/flows/src/app/transfer-and-pay-flow/own-account.service.ts
  apps/flows/src/app/transfer-and-pay-flow/transfer-and-pay-flow.component.ts
  package.json
Labels: ignore-for-release

#2626 changed ts formatter to 'Prettier'
  .vscode/settings.json
Labels: housekeeping

#2616 Add "add-bank" icon
  libs/designsystem/src/lib/components/icon/kirby-icon-settings.ts
  libs/designsystem/src/lib/icons/svg/add-bank.svg
Labels: enhancement

#2634 Add prettier formating for HTML
  .vscode/settings.json
Labels: housekeeping, ignore-for-release

#2637 Fix slide-button interaction limitations
  libs/designsystem/src/lib/components/slide-button/slide-button.component.scss
Labels: component:Slide Button, fix

#2615 Introduce new Stock Chart base config
  apps/cookbook/src/app/examples/charts-example/charts-example.module.ts
  apps/cookbook/src/app/examples/charts-example/examples/stock-config/chart-config-example.ts
  apps/cookbook/src/app/examples/charts-example/examples/stock-config/chart-example-config-base-stock.component.ts
  apps/cookbook/src/app/examples/charts-example/examples/stock-config/chart-example-config-datalabels-stock.component.ts
  apps/cookbook/src/app/examples/charts-example/examples/stock-config/chart-example-config-stock.component.ts
  apps/cookbook/src/app/examples/charts-example/examples/stock-config/chart-example-config-tooltip-stock.component.ts
  apps/cookbook/src/app/guides/chart-config-guide/chart-config-guide.component.html
  apps/cookbook/src/app/guides/chart-config-guide/chart-config-guide.component.ts
  apps/cookbook/src/app/guides/guides-routing.module.ts
  apps/cookbook/src/app/guides/guides.component.html
  apps/cookbook/src/app/guides/guides.module.ts
  apps/cookbook/src/app/showcase/chart-config-showcase/chart-config-showcase.component.html
  apps/cookbook/src/app/showcase/chart-config-showcase/chart-config-showcase.component.ts
  apps/cookbook/src/app/showcase/showcase.common.ts
  apps/cookbook/src/app/showcase/showcase.routes.ts
  libs/designsystem/src/lib/components/charts/chart-config/chart-base-config.ts
  libs/designsystem/src/lib/components/charts/chart-config/chart-stock-config/chart-stock-config.spec.ts
  libs/designsystem/src/lib/components/charts/chart-config/chart-stock-config/chart-stock-config.ts
  libs/designsystem/src/lib/components/charts/chart-config/chart-stock-config/data-label-position/data-label-position.ts
  libs/designsystem/src/lib/components/charts/chart-config/chart-stock-config/vertical-line-plugin/vertical-line-plugin.model.ts
  libs/designsystem/src/lib/components/charts/chart-config/chart-stock-config/vertical-line-plugin/vertical-line-plugin.ts
  libs/designsystem/src/lib/components/charts/chart-config/index.ts
  libs/designsystem/src/lib/components/charts/chart-options/chart-base-options.ts
  libs/designsystem/src/lib/components/charts/chart-options/chart-stock-options.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby-experimental.module.ts
Labels: feature
