Repository kirbydesign/designsystem, pull requests merged in 2022-12, with the labels that each got.

#2645 Add eslint rule to prevent focused tests
  .eslintrc.json
  package-lock.json
  package.json
Labels: ignore-for-release

#2646 Update build.yml deploy cookbook on pr-merge & tag
  .github/workflows/build.yml
Labels: ignore-for-release

#2649 Introduce new Stock Chart base config
  apps/cookbook/src/app/examples/charts-example/charts-example.module.ts
  apps/cookbook/src/app/examples/charts-example/examples/config/bar-config/chart-example-config-base-bar.component.ts
  apps/cookbook/src/app/examples/charts-example/examples/config/chart-config-example.ts
  apps/cookbook/src/app/examples/charts-example/examples/config/stock-config/chart-example-config-base-stock.component.ts
  apps/cookbook/src/app/examples/charts-example/examples/config/stock-config/chart-example-config-datalabels-stock.component.ts
  apps/cookbook/src/app/examples/charts-example/examples/config/stock-config/chart-example-config-stock.component.ts
  apps/cookbook/src/app/examples/charts-example/examples/config/stock-config/chart-example-config-tooltip-stock.component.ts
  apps/cookbook/src/app/guides/chart-config-guide/chart-config-guide.component.html
  apps/cookbook/src/app/guides/chart-config-guide/chart-config-guide.component.ts
  apps/cookbook/src/app/guides/guides.component.html
  apps/cookbook/src/app/showcase/chart-config-showcase/bar/chart-config-bar-showcase.component.html
  apps/cookbook/src/app/showcase/chart-config-showcase/bar/chart-config-bar-showcase.component.ts
  apps/cookbook/src/app/showcase/chart-config-showcase/chart-config-showcase.component.ts
  apps/cookbook/src/app/showcase/chart-config-showcase/stock/chart-config-stock-showcase.component.html
  apps/cookbook/src/app/showcase/chart-config-showcase/stock/chart-config-stock-showcase.component.ts
  apps/cookbook/src/app/showcase/showcase.common.ts
  apps/cookbook/src/app/showcase/showcase.routes.ts
  libs/designsystem/src/lib/components/charts/chart-config/chart-bar-config/chart-bar-config.ts
  libs/designsystem/src/lib/components/charts/chart-config/chart-base-config.ts
  libs/designsystem/src/lib/components/charts/chart-config/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby-experimental.module.ts
Labels: feature

#2636 Replace avatar with image shadow with stroke
  apps/cookbook/src/app/examples/avatar-example/examples/avatar-examples.shared.scss
  apps/cookbook/src/app/examples/avatar-example/examples/image.ts
  apps/cookbook/src/app/showcase/avatar-showcase/avatar-showcase.component.ts
  libs/designsystem/src/lib/components/avatar/avatar.component.html
  libs/designsystem/src/lib/components/avatar/avatar.component.scss
  libs/designsystem/src/lib/components/avatar/avatar.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.avatar.component.ts
Labels: feature

#2660 changed _utils forward to get stylesheet from relative path in node_m…
  libs/core/src/scss/_utils.scss
  libs/core/src/scss/themes/_colors.scss
  package-lock.json
Labels: housekeeping

#2661 Disable Kirby Christmas
  apps/cookbook/src/app/app.component.html
Labels: ignore-for-release

#2663 Add include-media to base styles instead of npm package
  libs/core/src/scss/_utils.scss
  libs/core/src/scss/base/_include-media.scss
  libs/designsystem/package.json
  package-lock.json
  package.json
  scripts/forward-scss-files.js
Labels: fix

#2656 Upgrade to angular 15
  .browserslistrc
  apps/cookbook/src/app/app-routing.module.ts
  apps/cookbook/src/app/examples/dropdown-example/examples/ng-forms.ts
  apps/cookbook/src/app/examples/radio-example/examples/reactive-forms.ts
  apps/cookbook/src/app/showcase/section-header-showcase/section-header-showcase.component.scss
  apps/cookbook/src/test.ts
  apps/cookbook/tsconfig.json
  apps/cookbook/tsconfig.spec.json
  apps/flows/.browserslistrc
  apps/flows/tsconfig.app.json
  apps/flows/tsconfig.json
  libs/designsystem/src/lib/components/form-field/directives/decimal-mask/decimal-mask.directive.spec.ts
  libs/designsystem/src/lib/components/list/list.component.integration.spec.ts
  libs/designsystem/src/lib/components/radio/radio-group/radio-group.component.spec.ts
  libs/designsystem/src/lib/helpers/deep-copy.ts
  libs/designsystem/src/lib/testing/element-css-custom-matchers.ts
  libs/designsystem/src/test.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.lib.json
  libs/designsystem/tsconfig.spec.json
  package-lock.json
  package.json
  project.json
  readme.md
  tools/generate-mocks/generate-mocks.ts
  tools/sass-to-ts/sass-to-ts-webpack.plugin.ts
Labels: breaking-change, housekeeping

#2678 Reorganize package scripts
  package.json
Labels: enhancement, ignore-for-release

#2680 Fix cookbook examples after Angular 15 upgrade
  apps/cookbook/src/app/examples/examples.routes.ts
Labels: ignore-for-release

#2687 Fix generateMock script after Angular 15 upgrade
  tools/generate-mocks/generate-mocks.ts
Labels: ignore-for-release

#2664 added z-index for sticky page content
  libs/core/src/scss/base/_variables.scss
  libs/designsystem/src/lib/components/page/page.component.scss
Labels: fix

#2528 Change modal from card modal to a fullscreen modal
  apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.html
  apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.ts
  apps/flows/android/app/capacitor.build.gradle
  apps/flows/android/capacitor.settings.gradle
  apps/flows/ios/App/App.xcodeproj/project.pbxproj
  apps/flows/ios/App/App/Info.plist
  apps/flows/ios/App/Podfile
  apps/flows/src/app/app.component.html
  apps/flows/src/app/app.component.ts
  apps/flows/src/app/home/home.component.html
  apps/flows/src/app/transfer-and-pay-flow/home-page/home-page.component.html
  apps/flows/src/app/transfer-and-pay-flow/transfer-and-pay-flow.component.html
  apps/flows/src/index.html
  libs/designsystem/src/lib/components/app/app.component.spec.ts
  libs/designsystem/src/lib/components/app/app.component.ts
  libs/designsystem/src/lib/components/modal/services/modal.controller.ts
  libs/designsystem/src/lib/components/modal/services/modal.helper.ts
  libs/designsystem/testing-jasmine/src/lib/mock-providers.ts
  libs/designsystem/testing-jest/src/lib/mock-providers.ts
  package-lock.json
  package.json
Labels: feature

#2682 Housekeeping/2681 remove unused libraries
  package-lock.json
  package.json
  readme.md
Labels: housekeeping, ignore-for-release

#2691 Fix missing back navigation arrow on stacked pages
  libs/designsystem/src/lib/components/button/button.component.scss
  libs/designsystem/src/lib/components/page/page.component.scss
  libs/designsystem/src/lib/components/page/page.component.ts
Labels: bug

#2696 Move packages to peerDependencies in designsystem package.json
  libs/designsystem/package.json
  package-lock.json
  package.json
Labels: enhancement, breaking-change

#2699 Remove deprecated Chip component
  libs/designsystem/src/lib/components/chip/chip.component.html
  libs/designsystem/src/lib/components/chip/chip.component.scss
  libs/designsystem/src/lib/components/chip/chip.component.spec.ts
  libs/designsystem/src/lib/components/chip/chip.component.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.spec.ts
  libs/designsystem/src/lib/directives/element-as-button/element-as-button.directive.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/testing-base/src/lib/components/index.ts
  libs/designsystem/testing-base/src/lib/components/mock.chip.component.ts
  libs/designsystem/testing-base/src/lib/mock-components.ts
Labels: breaking-change

#2693 [Bug] Fix kirby-page title animation when changing query params
  libs/designsystem/src/lib/components/page/page.component.spec.ts
  libs/designsystem/src/lib/components/page/page.component.ts
Labels: bug, component:Page, fix

#2700 Remove ResizeObserver polyfill
  apps/cookbook/src/index.html
  libs/designsystem/src/lib/components/card/card.component.ts
  libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.ts
  libs/designsystem/src/lib/components/shared/index.ts
  libs/designsystem/src/lib/components/shared/resize-observer/resize-observer.factory.ts
  libs/designsystem/src/lib/components/shared/resize-observer/resize-observer.service.ts
  libs/designsystem/src/lib/components/shared/resize-observer/types/resize-observer-callback.ts
  libs/designsystem/src/lib/components/shared/resize-observer/types/resize-observer-entry.ts
  libs/designsystem/src/lib/components/shared/resize-observer/types/resize-observer.ts
  libs/designsystem/src/lib/polyfills/resize-observer-polyfill-loader.js
  libs/designsystem/src/lib/polyfills/resize-observer-polyfill.js
  package-lock.json
  package.json
  readme.md
  webpack.polyfills.config.js
Labels: breaking-change

#2703 Apply focus ring to the segmented control only when using tab navigation
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.scss
Labels: feature
