Repository kirbydesign/designsystem, pull requests merged in 2023-02, with the labels that each got.

#2823 Item-group as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/item-group/index.ts
  libs/designsystem/item-group/ng-package.json
  libs/designsystem/item-group/src/index.ts
  libs/designsystem/item-group/src/item-group.component.html
  libs/designsystem/item-group/src/item-group.component.scss
  libs/designsystem/item-group/src/item-group.component.spec.ts
  libs/designsystem/item-group/src/item-group.component.ts
  libs/designsystem/item-group/src/public_api.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2817 Add routing to experimental modal component
  apps/cookbook/src/app/examples/modal-experimental-example/fullscreen/fullscreen-experimental-example.component.html
  apps/cookbook/src/app/examples/modal-experimental-example/modal-experimental-example.module.ts
  apps/cookbook/src/app/examples/modal-experimental-example/modal-routing/modal-routing-experimental-example-page1.component.ts
  apps/cookbook/src/app/examples/modal-experimental-example/modal-routing/modal-routing-experimental-example-page2.component.ts
  apps/cookbook/src/app/examples/modal-experimental-example/modal-routing/modal-routing-experimental-example.component.html
  apps/cookbook/src/app/examples/modal-experimental-example/modal-routing/modal-routing-experimental-example.component.ts
  apps/cookbook/src/app/showcase/modal-experimental-showcase/modal-experimental-showcase.component.html
  apps/cookbook/src/app/showcase/modal-experimental-showcase/modal-experimental-showcase.component.ts
  apps/cookbook/src/app/showcase/showcase.routes.ts
  libs/designsystem/item-group/ng-package.json
  libs/designsystem/modal/experimental/src/kirby-modal.module.ts
  libs/designsystem/modal/experimental/src/modal-routing/modal-routing.component.html
  libs/designsystem/modal/experimental/src/modal-routing/modal-routing.component.scss
  libs/designsystem/modal/experimental/src/modal-routing/modal-routing.component.ts
  libs/designsystem/modal/experimental/src/public_api.ts
Labels: feature

#2833 Add missing exports
  libs/designsystem/src/lib/index.ts
Labels: ignore-for-release, fix

#2835 chart as secondary entry
  apps/cookbook/src/app/examples/charts-example/examples/chart-example-column-stacked.component.ts
  apps/cookbook/src/app/examples/charts-example/examples/chart-example-interaction.component.ts
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/chart/index.ts
  libs/designsystem/chart/ng-package.json
  libs/designsystem/chart/src/chart-config/chart-bar-config/chart-bar-config.ts
  libs/designsystem/chart/src/chart-config/chart-base-config.ts
  libs/designsystem/chart/src/chart-config/chart-stock-config/chart-stock-config.spec.ts
  libs/designsystem/chart/src/chart-config/chart-stock-config/chart-stock-config.ts
  libs/designsystem/chart/src/chart-config/chart-stock-config/data-label-position/data-label-position.ts
  libs/designsystem/chart/src/chart-config/chart-stock-config/vertical-line-plugin/vertical-line-plugin.model.ts
  libs/designsystem/chart/src/chart-config/chart-stock-config/vertical-line-plugin/vertical-line-plugin.ts
  libs/designsystem/chart/src/chart-config/index.ts
  libs/designsystem/chart/src/chart-options/chart-base-options.ts
  libs/designsystem/chart/src/chart-options/chart-stock-options.ts
  libs/designsystem/chart/src/chart/chart.component.spec.ts
  libs/designsystem/chart/src/chart/chart.component.ts
  libs/designsystem/chart/src/chart/index.ts
  libs/designsystem/chart/src/charts.module.ts
  libs/designsystem/chart/src/public_api.ts
  libs/designsystem/chart/src/shared/base-chart/base-chart.component.html
  libs/designsystem/chart/src/shared/base-chart/base-chart.component.scss
  libs/designsystem/chart/src/shared/base-chart/base-chart.component.ts
  libs/designsystem/chart/src/shared/base-chart/index.ts
  libs/designsystem/chart/src/shared/chart-config-service/chart-config.service.spec.ts
  libs/designsystem/chart/src/shared/chart-config-service/chart-config.service.ts
  libs/designsystem/chart/src/shared/chart-config-service/configs/annotations.config.ts
  libs/designsystem/chart/src/shared/chart-config-service/configs/global-defaults.config.ts
  libs/designsystem/chart/src/shared/chart-config-service/configs/interaction-functions-extensions.config.ts
  libs/designsystem/chart/src/shared/chart-config-service/configs/type.config.ts
  libs/designsystem/chart/src/shared/chart-config-service/index.ts
  libs/designsystem/chart/src/shared/chart-js-service/annotations.delegate.ts
  libs/designsystem/chart/src/shared/chart-js-service/chart-js.service.integration.spec.ts
  libs/designsystem/chart/src/shared/chart-js-service/chart-js.service.spec.ts
  libs/designsystem/chart/src/shared/chart-js-service/chart-js.service.ts
  libs/designsystem/chart/src/shared/chart-js-service/chartjs-plugin-marker/chartjs-plugin-marker.ts
  libs/designsystem/chart/src/shared/chart-js-service/configured-chart-js.ts
  libs/designsystem/chart/src/shared/chart-js-service/index.ts
  libs/designsystem/chart/src/shared/chart-js-service/test-utils.ts
  libs/designsystem/chart/src/shared/charts.types.ts
  libs/designsystem/chart/src/shared/index.ts
  libs/designsystem/chart/src/stock-chart/index.ts
  libs/designsystem/chart/src/stock-chart/stock-chart-js.service.integration.spec.ts
  libs/designsystem/chart/src/stock-chart/stock-chart-js.service.spec.ts
  libs/designsystem/chart/src/stock-chart/stock-chart-js.service.ts
  libs/designsystem/chart/src/stock-chart/stock-chart.component.ts
  libs/designsystem/src/lib/components/charts/index.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby-experimental.module.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/testing-base/src/lib/components/mock.base-chart.component.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement

#2841 fab-sheet as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/fab-sheet/index.ts
  libs/designsystem/fab-sheet/ng-package.json
  libs/designsystem/fab-sheet/src/fab-sheet.component.html
  libs/designsystem/fab-sheet/src/fab-sheet.component.scss
  libs/designsystem/fab-sheet/src/fab-sheet.component.spec.ts
  libs/designsystem/fab-sheet/src/fab-sheet.component.ts
  libs/designsystem/fab-sheet/src/index.ts
  libs/designsystem/fab-sheet/src/public_api.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2842 ScssHelper as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/helpers/scss/index.ts
  libs/designsystem/helpers/scss/ng-package.json
  libs/designsystem/helpers/scss/src/index.ts
  libs/designsystem/helpers/scss/src/link.spec.ts
  libs/designsystem/helpers/scss/src/public_api.ts
  libs/designsystem/helpers/scss/src/scss-helper.ts
  libs/designsystem/helpers/scss/src/typography.spec.ts
  libs/designsystem/src/lib/components/grid/grid.component.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2839 data-table as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/data-table/index.ts
  libs/designsystem/data-table/ng-package.json
  libs/designsystem/data-table/src/data-table.module.ts
  libs/designsystem/data-table/src/index.ts
  libs/designsystem/data-table/src/public_api.ts
  libs/designsystem/data-table/src/table-row/table-row.component.spec.ts
  libs/designsystem/data-table/src/table-row/table-row.component.ts
  libs/designsystem/data-table/src/table/table.component.scss
  libs/designsystem/data-table/src/table/table.component.spec.ts
  libs/designsystem/data-table/src/table/table.component.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/testing-base/src/lib/components/mock.table.component.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2845 Remove reintroduced polyfills
  libs/designsystem/src/lib/polyfills/intersection-observer-polyfill-loader.min.js
  libs/designsystem/src/lib/polyfills/intersection-observer-polyfill.min.js
Labels: ignore-for-release

#2846 reroder list as secondary entry
  apps/cookbook/src/app/examples/reorder-list-example/reorder-list-example.component.ts
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/reorder-list/index.ts
  libs/designsystem/reorder-list/ng-package.json
  libs/designsystem/reorder-list/src/index.ts
  libs/designsystem/reorder-list/src/public_api.ts
  libs/designsystem/reorder-list/src/reorder-event.ts
  libs/designsystem/reorder-list/src/reorder-list.component.html
  libs/designsystem/reorder-list/src/reorder-list.component.scss
  libs/designsystem/reorder-list/src/reorder-list.component.spec.ts
  libs/designsystem/reorder-list/src/reorder-list.component.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2851 Add banknotes, air-balloon, piggybank and business icons
  libs/designsystem/icon/src/icons/svg/air-balloon.svg
  libs/designsystem/icon/src/icons/svg/banknotes.svg
  libs/designsystem/icon/src/icons/svg/business.svg
  libs/designsystem/icon/src/icons/svg/piggybank.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: feature

#2852 Rename the experimental modal component
  apps/cookbook/src/app/examples/modal-experimental-example/fullscreen/fullscreen-experimental-example.component.html
  apps/cookbook/src/app/examples/modal-experimental-example/fullscreen/fullscreen-experimental-example.component.ts
  libs/designsystem/modal/experimental/src/kirby-modal.module.ts
  libs/designsystem/modal/experimental/src/modal/modal.component.html
  libs/designsystem/modal/experimental/src/modal/modal.component.scss
  libs/designsystem/modal/experimental/src/modal/modal.component.spec.ts
  libs/designsystem/modal/experimental/src/modal/modal.component.ts
  libs/designsystem/modal/experimental/src/public_api.ts
Labels: feature

#2850 toast as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/testing-jasmine/src/lib/mock-providers.ts
  libs/designsystem/testing-jest/src/lib/mock-providers.ts
  libs/designsystem/toast/index.ts
  libs/designsystem/toast/ng-package.json
  libs/designsystem/toast/src/config/toast-config.ts
  libs/designsystem/toast/src/index.ts
  libs/designsystem/toast/src/public_api.ts
  libs/designsystem/toast/src/services/indexs.ts
  libs/designsystem/toast/src/services/toast.controller.ts
  libs/designsystem/toast/src/services/toast.helper.spec.ts
  libs/designsystem/toast/src/services/toast.helper.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2847 grid as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/grid/index.ts
  libs/designsystem/grid/ng-package.json
  libs/designsystem/grid/src/breakpoint-helper.service.ts
  libs/designsystem/grid/src/grid-card-configuration.ts
  libs/designsystem/grid/src/grid.component.html
  libs/designsystem/grid/src/grid.component.scss
  libs/designsystem/grid/src/grid.component.ts
  libs/designsystem/grid/src/index.ts
  libs/designsystem/grid/src/public_api.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2856 removed packages from `allowedNonPeerDependencies`
  libs/designsystem/ng-package.json
Labels: enhancement, ignore-for-release

#2865 Fix kirby-button attentionLevel 3 in list & modal footer
  MIGRATION.md
  libs/designsystem/list/src/list.component.scss
  libs/designsystem/modal/experimental/src/footer/footer.component.scss
  libs/designsystem/modal/src/modal/footer/modal-footer.component.scss
Labels: fix

#2866 Fix kirby-button attentionLevel 3 in kirby-page-footer
  libs/designsystem/page/src/page-footer/page-footer.component.scss
Labels: fix

#2884 Fix date mask directive in form field
  .nvmrc
  libs/designsystem/form-field/src/form-field.module.ts
  package.json
Labels: fix

#2883 Fix failing workflow runs caused by node v18.14
  .nvmrc
  package.json
Labels: ignore-for-release

#2886 Fix date mask directive in form field
  libs/designsystem/form-field/src/form-field.module.ts
Labels: fix

#2890 Hotfix Release v8.1.1: Add CommonModule in standalone comps
  libs/core/package.json
  libs/designsystem/button/src/button.component.ts
  libs/designsystem/divider/src/divider.component.ts
  libs/designsystem/flag/src/flag.component.ts
  libs/designsystem/form-field/src/input/input.component.ts
  libs/designsystem/grid/src/grid.component.ts
  libs/designsystem/item-group/src/item-group.component.ts
  libs/designsystem/modal/src/modal/footer/modal-footer.component.ts
  libs/designsystem/package.json
  libs/designsystem/popover/src/popover.component.ts
  libs/designsystem/progress-circle/src/progress-circle-ring.component.ts
  libs/designsystem/progress-circle/src/progress-circle.component.ts
  libs/designsystem/section-header/src/section-header.component.ts
  libs/designsystem/toggle/src/toggle.component.ts
  package-lock.json
  package.json
Labels: fix

#2871 Experimental Alert
  apps/cookbook/src/app/examples/alert-experimental-example/alert-experimental-example.component.html
  apps/cookbook/src/app/examples/alert-experimental-example/alert-experimental-example.component.ts
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/showcase/alert-experimental-showcase/alert-experimental-showcase.component.html
  apps/cookbook/src/app/showcase/alert-experimental-showcase/alert-experimental-showcase.component.ts
  apps/cookbook/src/app/showcase/showcase.common.ts
  apps/cookbook/src/app/showcase/showcase.routes.ts
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/alert-experimental/index.ts
  libs/designsystem/alert-experimental/ng-package.json
  libs/designsystem/alert-experimental/src/alert.component.html
  libs/designsystem/alert-experimental/src/alert.component.scss
  libs/designsystem/alert-experimental/src/alert.component.spec.ts
  libs/designsystem/alert-experimental/src/alert.component.ts
  libs/designsystem/alert-experimental/src/alert.module.ts
  libs/designsystem/alert-experimental/src/config/alert-config.ts
  libs/designsystem/alert-experimental/src/index.ts
  libs/designsystem/alert-experimental/src/public_api.ts
  libs/designsystem/alert-experimental/src/services/alert.controller.spec.ts
  libs/designsystem/alert-experimental/src/services/alert.controller.ts
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/src/lib/index.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: feature

#2711 Enable strict template checks
  libs/designsystem/alert-experimental/src/alert.component.ts
  libs/designsystem/list/src/list-item/list-item.component.ts
  libs/designsystem/modal/src/modal/alert/alert.component.ts
  libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation-item.ts
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts
  libs/designsystem/tsconfig.lib.json
Labels: ignore-for-release

#2876 Add portal directive
  libs/designsystem/shared/src/portal/index.ts
  libs/designsystem/shared/src/portal/ng-package.json
  libs/designsystem/shared/src/portal/src/index.ts
  libs/designsystem/shared/src/portal/src/portal.directive.spec.ts
  libs/designsystem/shared/src/portal/src/portal.directive.ts
  libs/designsystem/shared/src/portal/src/public_api.ts
Labels: feature

#2900 Fix misaligned dates and weekdays in calendar
  apps/cookbook/src/app/examples/calendar-example/calendar-locales-examples.ts
  apps/cookbook/src/app/showcase/calendar-showcase/calendar-showcase.component.html
  apps/cookbook/src/app/showcase/calendar-showcase/calendar-showcase.component.ts
  libs/designsystem/calendar/src/calendar.component.spec.ts
  libs/designsystem/calendar/src/calendar.component.ts
  package-lock.json
  package.json
Labels: fix
