Repository kirbydesign/designsystem, pull requests merged in 2023-04, with the labels that each got.

#2993 Add document and chat icons
  libs/designsystem/icon/src/icons/svg/chat.svg
  libs/designsystem/icon/src/icons/svg/document.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: enhancement, feature

#3006 Remove space between tabs of tab-nav
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.scss
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.scss
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.ts
Labels: fix

#3010 added warning about missing directive declaration
  apps/cookbook/src/app/showcase/form-field-showcase/form-field-showcase.component.html
Labels: documentation, ignore-for-release

#2976 Remove min-width on dropdown
  libs/designsystem/dropdown/src/dropdown.component.scss
Labels: fix

#2988 Fix menu in header actions
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/header-example/examples/action-group.ts
  apps/cookbook/src/app/examples/header-example/examples/custom-actions.ts
  apps/cookbook/src/app/examples/menu-example/examples/advanced.ts
  apps/cookbook/src/app/examples/menu-example/examples/selectable.ts
  apps/cookbook/src/app/showcase/header-showcase/header-showcase.component.html
  apps/cookbook/src/app/showcase/header-showcase/header-showcase.component.ts
  apps/cookbook/src/app/showcase/menu-showcase/menu-showcase.component.html
  apps/cookbook/src/app/showcase/menu-showcase/menu-showcase.component.ts
  libs/designsystem/action-group/src/action-group.component.ts
  libs/designsystem/button/src/button.component.ts
  libs/designsystem/header/src/header.component.scss
  libs/designsystem/header/src/header.component.ts
  libs/designsystem/item/src/item.component.scss
  libs/designsystem/menu/src/menu.component.html
  libs/designsystem/menu/src/menu.component.spec.ts
  libs/designsystem/menu/src/menu.component.ts
  libs/designsystem/page/src/page.component.html
  libs/designsystem/page/src/page.component.ts
  libs/designsystem/shared/floating/src/floating.directive.spec.ts
  libs/designsystem/shared/floating/src/floating.directive.ts
Labels: fix

#3015 Make the cookbook side-nav scrollable on smaller viewports
  apps/cookbook/src/app/page/side-nav/side-nav.component.scss
Labels: ignore-for-release

#3014 Undecorated button has background color
  apps/cookbook/src/app/examples/button-example/button-example.component.html
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/button/src/button.component.spec.ts
Labels: fix
