Repository kirbydesign/designsystem, pull requests merged in 2023-01, with the labels that each got.

#2701 Remove IntersectionObserver polyfill
  .gitignore
  angular.json
  apps/cookbook/src/index.html
  libs/designsystem/src/lib/components/shared/resize-observer/resize-observer.service.ts
  libs/designsystem/src/lib/polyfills/intersection-observer-polyfill-loader.js
  libs/designsystem/src/lib/polyfills/intersection-observer-polyfill.js
  package.json
  scripts/publish.js
  webpack.polyfills.config.js
Labels: breaking-change

#2695 Redo RxJS 7 upgrade
  libs/designsystem/package.json
  libs/designsystem/src/lib/components/modal/modal-wrapper/compact/modal-compact-wrapper.component.ts
  libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.ts
  libs/designsystem/src/lib/components/modal/services/modal-navigation.service.ts
Labels: breaking-change

#2698 Refactor how kirby list items receive hover effect
  MIGRATION.md
  apps/cookbook/src/app/examples/list-example/examples/colored-items.ts
  apps/cookbook/src/app/examples/list-example/examples/header-and-footer.ts
  apps/cookbook/src/app/examples/list-example/examples/sections-and-colored-items.ts
  apps/cookbook/src/app/examples/list-example/examples/sections-with-standalone.ts
  apps/cookbook/src/app/examples/list-example/examples/sections.ts
  apps/cookbook/src/app/examples/list-example/examples/selectable-items.ts
  apps/cookbook/src/app/examples/list-example/examples/stand-alone.ts
  apps/cookbook/src/app/showcase/list-showcase/list-showcase.component.html
  libs/designsystem/src/lib/components/item/item.component.html
  libs/designsystem/src/lib/components/item/item.component.ts
  libs/designsystem/src/lib/components/list/list.component.ts
Labels: breaking-change

#2712 Slides use Ion hook for initial slide position
  libs/designsystem/src/lib/components/slides/slides.component.spec.ts
  libs/designsystem/src/lib/components/slides/slides.component.ts
Labels: enhancement

#2713 Kirby page sticky content shouldn't be transparent
  libs/designsystem/src/lib/components/page/page.component.scss
Labels: bug, fix

#2722 Generate missing mocks
  libs/designsystem/testing-base/src/lib/components/index.ts
  libs/designsystem/testing-base/src/lib/components/mock.dropdown.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.page-local-navigation.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.page.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.table-row.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.table.component.ts
  libs/designsystem/testing-base/src/lib/mock-components.ts
  libs/designsystem/testing-base/testing-jasmine/src/lib/mock-providers.ts
  libs/designsystem/testing-jest/src/lib/mock-providers.ts
Labels: ignore-for-release

#2723 Update package-lock file
  package-lock.json
Labels: housekeeping, ignore-for-release

#2724 Enhancement/move 'element-as-button' directive to card entry
  libs/designsystem/card/src/card-as-button/card-as-button.directive.spec.ts
  libs/designsystem/card/src/card-as-button/card-as-button.directive.ts
  libs/designsystem/card/src/card.module.ts
  libs/designsystem/card/src/public_api.ts
  libs/designsystem/src/lib/directives/index.ts
  libs/designsystem/src/lib/kirby.module.ts
Labels: enhancement

#2728 Enhancement/flag as secondary entry
  apps/cookbook/tsconfig.json
  libs/designsystem/flag/index.ts
  libs/designsystem/flag/ng-package.json
  libs/designsystem/flag/src/flag.component.scss
  libs/designsystem/flag/src/flag.component.spec.ts
  libs/designsystem/flag/src/flag.component.ts
  libs/designsystem/flag/src/index.ts
  libs/designsystem/flag/src/public_api.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/components/radio/radio-group/radio-group.component.spec.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement

#2448 [Enhancement] Range should only emit change event on ion change
  libs/designsystem/src/lib/components/range/range.component.ts
Labels: breaking-change

#2710 Add option to hide content behind a non-transparent loading overlay
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/examples/loading-overlay-example/loading-overlay-example.component.html
  apps/cookbook/src/app/examples/loading-overlay-example/loading-overlay-example.component.ts
  apps/cookbook/src/app/examples/loading-overlay-example/service/loading-overlay-service-example.component.html
  apps/cookbook/src/app/examples/loading-overlay-example/service/loading-overlay-service-example.component.ts
  apps/cookbook/src/app/examples/loading-overlay-example/service/loading-overlay-service-example.ts
  apps/cookbook/src/app/showcase/loading-overlay-showcase/loading-overlay-showcase.component.html
  apps/cookbook/src/app/showcase/loading-overlay-showcase/loading-overlay-showcase.component.ts
  libs/core/src/scss/_global-styles.scss
  libs/designsystem/src/lib/components/loading-overlay/loading-overlay.component.html
  libs/designsystem/src/lib/components/loading-overlay/loading-overlay.component.scss
  libs/designsystem/src/lib/components/loading-overlay/loading-overlay.component.ts
  libs/designsystem/src/lib/components/loading-overlay/loading-overlay.service.ts
Labels: feature

#2732 Add secondary entry for flag to flows tsconfig
  apps/flows/tsconfig.json
Labels: ignore-for-release

#2729 Add row and columns specific spacing for Grid
  apps/cookbook/src/app/examples/grid-example/grid-example.component.html
  apps/cookbook/src/app/examples/grid-example/grid-example.component.ts
  apps/cookbook/src/app/showcase/grid-showcase/grid-showcase.component.ts
  libs/core/src/scss/components/_grid.scss
Labels: enhancement, feature

#2731 Spinner as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/spinner/index.ts
  libs/designsystem/spinner/ng-package.json
  libs/designsystem/spinner/src/index.ts
  libs/designsystem/spinner/src/public_api.ts
  libs/designsystem/spinner/src/spinner.component.html
  libs/designsystem/spinner/src/spinner.component.scss
  libs/designsystem/spinner/src/spinner.component.ts
  libs/designsystem/spinner/src/spinner.module.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/components/list/list.component.integration.spec.ts
  libs/designsystem/src/lib/components/list/list.component.spec.ts
  libs/designsystem/src/lib/components/list/list.module.ts
  libs/designsystem/src/lib/components/loading-overlay/loading-overlay.component.ts
  libs/designsystem/src/lib/components/loading-overlay/loading-overlay.service.ts
  libs/designsystem/src/lib/components/modal/action-sheet/action-sheet.component.spec.ts
  libs/designsystem/src/lib/components/page/page.module.ts
  libs/designsystem/src/lib/components/radio/radio-group/radio-group.component.spec.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2738 Housekeeping/2736 tempoarily remove flaky tests
  libs/designsystem/src/lib/components/dropdown/dropdown.component.spec.ts
  libs/designsystem/src/lib/components/modal/footer/modal-footer.component.spec.ts
  libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.spec.ts
  libs/designsystem/src/lib/components/modal/services/modal.helper.spec.ts
  libs/designsystem/src/lib/components/radio/radio-group/radio-group.component.spec.ts
Labels: housekeeping, ignore-for-release, fix

#2742 Only add API table scrollbar when content overflows
  apps/cookbook/src/app/shared/api-description/api-description.shared.scss
Labels: ignore-for-release

#2746 added toggle
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/testing-base/src/lib/components/mock.toggle.component.ts
  libs/designsystem/toggle/index.ts
  libs/designsystem/toggle/ng-package.json
  libs/designsystem/toggle/src/index.ts
  libs/designsystem/toggle/src/public_api.ts
  libs/designsystem/toggle/src/toggle.component.html
  libs/designsystem/toggle/src/toggle.component.scss
  libs/designsystem/toggle/src/toggle.component.spec.ts
  libs/designsystem/toggle/src/toggle.component.ts
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2702 Add option to provide additional locales to kirby-calendar and add locale documentation
  apps/cookbook/src/app/examples/calendar-example/calendar-locales-examples.ts
  apps/cookbook/src/app/showcase/calendar-showcase/calendar-showcase.component.html
  apps/cookbook/src/app/showcase/calendar-showcase/calendar-showcase.component.ts
  libs/designsystem/src/lib/components/calendar/calendar.component.spec.ts
  libs/designsystem/src/lib/components/calendar/calendar.component.ts
  libs/designsystem/src/lib/components/calendar/index.ts
Labels: enhancement, feature

#2751 Improve kirby-page for desktop usage
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/page-example/base-page-example.component.ts
  apps/cookbook/src/app/examples/page-example/content-width/page-content-width-example.component.ts
  apps/cookbook/src/app/showcase/page-showcase/page-showcase.component.html
  apps/cookbook/src/app/showcase/page-showcase/page-showcase.component.ts
  libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.scss
  libs/designsystem/src/lib/components/page/page.component.html
  libs/designsystem/src/lib/components/page/page.component.scss
  libs/designsystem/src/lib/components/page/page.component.spec.ts
  libs/designsystem/src/lib/components/page/page.component.ts
Labels: enhancement, component:Page, feature

#2756 Configure test setup to include test files in secondary entries
  angular.json
  libs/designsystem/test.ts
  libs/designsystem/tsconfig.spec.json
Labels: ignore-for-release

#2755 Item and section-header as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/core/src/scss/base/_functions.scss
  libs/designsystem/item/index.ts
  libs/designsystem/item/ng-package.json
  libs/designsystem/item/src/_item.utils.scss
  libs/designsystem/item/src/index.ts
  libs/designsystem/item/src/item.component.html
  libs/designsystem/item/src/item.component.integration.spec.ts
  libs/designsystem/item/src/item.component.scss
  libs/designsystem/item/src/item.component.spec.ts
  libs/designsystem/item/src/item.component.ts
  libs/designsystem/item/src/item.module.ts
  libs/designsystem/item/src/label/label.component.html
  libs/designsystem/item/src/label/label.component.scss
  libs/designsystem/item/src/label/label.component.spec.ts
  libs/designsystem/item/src/label/label.component.ts
  libs/designsystem/item/src/public_api.ts
  libs/designsystem/section-header/index.ts
  libs/designsystem/section-header/ng-package.json
  libs/designsystem/section-header/src/_section-header.utils.scss
  libs/designsystem/section-header/src/index.ts
  libs/designsystem/section-header/src/public_api.ts
  libs/designsystem/section-header/src/section-header.component.html
  libs/designsystem/section-header/src/section-header.component.scss
  libs/designsystem/section-header/src/section-header.component.spec.ts
  libs/designsystem/section-header/src/section-header.component.ts
  libs/designsystem/section-header/src/section-header.integration.spec.ts
  libs/designsystem/src/lib/components/button/button.component.integration.spec.ts
  libs/designsystem/src/lib/components/checkbox/checkbox.component.integration.spec.ts
  libs/designsystem/src/lib/components/dropdown/dropdown-popover.component.integration.spec.ts
  libs/designsystem/src/lib/components/dropdown/dropdown-popover.component.spec.ts
  libs/designsystem/src/lib/components/dropdown/dropdown.component.spec.ts
  libs/designsystem/src/lib/components/dropdown/dropdown.component.ts
  libs/designsystem/src/lib/components/dropdown/dropdown.module.ts
  libs/designsystem/src/lib/components/form-field/form-field.component.spec.ts
  libs/designsystem/src/lib/components/form-field/input/input.component.integration.spec.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/components/item-group/item-group.component.spec.ts
  libs/designsystem/src/lib/components/list/list-experimental/list-experimental.component.spec.ts
  libs/designsystem/src/lib/components/list/list.component.integration.spec.ts
  libs/designsystem/src/lib/components/radio/radio.component.integration.spec.ts
  libs/designsystem/src/lib/components/reorder-list/reorder-list.component.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/testing-base/src/lib/components/mock.item.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.label.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.section-header.component.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2757 Fix the todayDate prop causing errors in the flows app
  apps/flows/src/app/transfer-and-pay-flow/choose-date/choose-date.component.html
  apps/flows/src/app/transfer-and-pay-flow/choose-date/choose-date.component.ts
Labels: housekeeping

#2759 Slide as secondary entry
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/examples/slides-example/slides-example.component.ts
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/slide/index.ts
  libs/designsystem/slide/ng-package.json
  libs/designsystem/slide/src/index.ts
  libs/designsystem/slide/src/public_api.ts
  libs/designsystem/slide/src/slide.directive.ts
  libs/designsystem/slide/src/slide.module.ts
  libs/designsystem/slide/src/slides.component.spec.ts
  libs/designsystem/slide/src/slides.component.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/testing-base/src/lib/components/mock.slides.component.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2760 Toggle-button as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/testing-base/src/lib/components/mock.toggle-button.component.ts
  libs/designsystem/toggle-button/index.ts
  libs/designsystem/toggle-button/ng-package.json
  libs/designsystem/toggle-button/src/index.ts
  libs/designsystem/toggle-button/src/public_api.ts
  libs/designsystem/toggle-button/src/toggle-button.component.html
  libs/designsystem/toggle-button/src/toggle-button.component.spec.ts
  libs/designsystem/toggle-button/src/toggle-button.component.ts
  libs/designsystem/toggle-button/src/toggle-button.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2763 Tabs as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/components/page/page.component.spec.ts
  libs/designsystem/src/lib/components/page/page.component.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tabs/index.ts
  libs/designsystem/tabs/ng-package.json
  libs/designsystem/tabs/src/index.ts
  libs/designsystem/tabs/src/public_api.ts
  libs/designsystem/tabs/src/tab-button/tab-button.component.html
  libs/designsystem/tabs/src/tab-button/tab-button.component.scss
  libs/designsystem/tabs/src/tab-button/tab-button.component.spec.ts
  libs/designsystem/tabs/src/tab-button/tab-button.component.ts
  libs/designsystem/tabs/src/tab-button/tab-button.events.ts
  libs/designsystem/tabs/src/tabs.component.html
  libs/designsystem/tabs/src/tabs.component.scss
  libs/designsystem/tabs/src/tabs.component.spec.ts
  libs/designsystem/tabs/src/tabs.component.ts
  libs/designsystem/tabs/src/tabs.module.ts
  libs/designsystem/tabs/src/tabs.service.ts
  libs/designsystem/testing-base/src/lib/components/mock.tab-button.component.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2769 Add secondary modules exports
  libs/designsystem/src/lib/index.ts
Labels: housekeeping, ignore-for-release

#2778 slide-button as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/slide-button/index.ts
  libs/designsystem/slide-button/ng-package.json
  libs/designsystem/slide-button/src/index.ts
  libs/designsystem/slide-button/src/public_api.ts
  libs/designsystem/slide-button/src/slide-button.component.html
  libs/designsystem/slide-button/src/slide-button.component.scss
  libs/designsystem/slide-button/src/slide-button.component.spec.ts
  libs/designsystem/slide-button/src/slide-button.component.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/testing-base/src/lib/components/mock.slide-button.component.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2781 range as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/range/index.ts
  libs/designsystem/range/ng-package.json
  libs/designsystem/range/src/index.ts
  libs/designsystem/range/src/public_api.ts
  libs/designsystem/range/src/range.component.html
  libs/designsystem/range/src/range.component.scss
  libs/designsystem/range/src/range.component.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2782 popover as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/popover/index.ts
  libs/designsystem/popover/ng-package.json
  libs/designsystem/popover/src/index.ts
  libs/designsystem/popover/src/popover.component.scss
  libs/designsystem/popover/src/popover.component.spec.ts
  libs/designsystem/popover/src/popover.component.ts
  libs/designsystem/popover/src/public_api.ts
  libs/designsystem/src/lib/components/dropdown/dropdown-popover.component.integration.spec.ts
  libs/designsystem/src/lib/components/dropdown/dropdown-popover.component.spec.ts
  libs/designsystem/src/lib/components/dropdown/dropdown.component.spec.ts
  libs/designsystem/src/lib/components/dropdown/dropdown.component.ts
  libs/designsystem/src/lib/components/dropdown/dropdown.module.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
  package.json
Labels: enhancement, ignore-for-release

#2735 Introduce new attention level designs for button and related theming for card
  apps/cookbook/src/app/examples/dropdown-example/examples/attention-level.ts
  apps/cookbook/src/app/examples/dropdown-example/examples/dropdown-examples.shared.scss
  libs/core/src/scss/themes/_colors.scss
  libs/core/src/scss/themes/_component-themes.scss
  libs/core/src/scss/themes/_index.scss
  libs/designsystem/card/src/card.component.scss
  libs/designsystem/src/lib/components/avatar/avatar.component.spec.ts
  libs/designsystem/src/lib/components/button/button.component.integration.spec.ts
  libs/designsystem/src/lib/components/button/button.component.scss
  libs/designsystem/src/lib/components/button/button.component.spec.ts
  libs/designsystem/src/lib/components/dropdown/dropdown.component.html
  libs/designsystem/src/lib/components/dropdown/dropdown.component.ts
  libs/designsystem/src/lib/components/modal/action-sheet/action-sheet.component.html
  libs/designsystem/src/lib/components/modal/action-sheet/action-sheet.component.spec.ts
  libs/designsystem/src/lib/directives/theme-color/theme-color.directive.integration.spec.ts
Labels: feature

#2773 Themecolor as secondary entry
  libs/designsystem/card/src/card.module.ts
  libs/designsystem/icon/src/icon.module.ts
  libs/designsystem/shared/src/public_api.ts
  libs/designsystem/shared/src/theme-color/theme-color.directive.integration.spec.ts
  libs/designsystem/shared/src/theme-color/theme-color.directive.ts
  libs/designsystem/src/lib/components/avatar/avatar.component.spec.ts
  libs/designsystem/src/lib/components/avatar/avatar.component.ts
  libs/designsystem/src/lib/components/empty-state/empty-state.module.ts
  libs/designsystem/src/lib/components/modal/alert/alert.component.ts
  libs/designsystem/src/lib/components/modal/footer/modal-footer.component.spec.ts
  libs/designsystem/src/lib/components/modal/footer/modal-footer.component.ts
  libs/designsystem/src/lib/components/progress-circle/progress-circle-ring.component.ts
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.spec.ts
  libs/designsystem/src/lib/directives/index.ts
  libs/designsystem/src/lib/kirby.module.ts
Labels: ignore-for-release

#2783 loading-overlay as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/loading-overlay/index.ts
  libs/designsystem/loading-overlay/ng-package.json
  libs/designsystem/loading-overlay/src/index.ts
  libs/designsystem/loading-overlay/src/loading-overlay.component.html
  libs/designsystem/loading-overlay/src/loading-overlay.component.scss
  libs/designsystem/loading-overlay/src/loading-overlay.component.ts
  libs/designsystem/loading-overlay/src/loading-overlay.service.ts
  libs/designsystem/loading-overlay/src/public_api.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2766 Guide for secondary entries.
  libs/designsystem/secondary-entry.md
Labels: housekeeping, ignore-for-release

#2785 divider as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/divider/index.ts
  libs/designsystem/divider/ng-package.json
  libs/designsystem/divider/src/divider.component.html
  libs/designsystem/divider/src/divider.component.scss
  libs/designsystem/divider/src/divider.component.spec.ts
  libs/designsystem/divider/src/divider.component.ts
  libs/designsystem/divider/src/index.ts
  libs/designsystem/divider/src/public_api.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2786 Checkbox as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/checkbox/index.ts
  libs/designsystem/checkbox/ng-package.json
  libs/designsystem/checkbox/src/checkbox.component.html
  libs/designsystem/checkbox/src/checkbox.component.integration.spec.ts
  libs/designsystem/checkbox/src/checkbox.component.scss
  libs/designsystem/checkbox/src/checkbox.component.spec.ts
  libs/designsystem/checkbox/src/checkbox.component.ts
  libs/designsystem/checkbox/src/index.ts
  libs/designsystem/checkbox/src/public_api.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2784 Change icon in example to arrow-more
  apps/cookbook/src/app/examples/card-example/examples/card-with-item-header-example/card-with-item-header-example.component.html
  apps/cookbook/src/app/examples/card-example/examples/card-with-item-header-example/card-with-item-header-example.component.ts
Labels: enhancement

#2788 accordion as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/accordion/index.ts
  libs/designsystem/accordion/ng-package.json
  libs/designsystem/accordion/src/accordion-item.component.html
  libs/designsystem/accordion/src/accordion-item.component.scss
  libs/designsystem/accordion/src/accordion-item.component.spec.ts
  libs/designsystem/accordion/src/accordion-item.component.ts
  libs/designsystem/accordion/src/accordion.directive.ts
  libs/designsystem/accordion/src/accordion.module.ts
  libs/designsystem/accordion/src/index.ts
  libs/designsystem/accordion/src/public_api.ts
  libs/designsystem/src/lib/components/accordion/index.ts
  libs/designsystem/src/lib/components/calendar/calendar.component.initialization.spec.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
  package-lock.json
Labels: enhancement, ignore-for-release

#2793 Now sets URL for example component immediately on page showcase initialization
  apps/cookbook/src/app/showcase/showcase.component.ts
Labels: ignore-for-release

#2787 Improve card documentation
  apps/cookbook/src/app/examples/card-example/card-example.component.html
  apps/cookbook/src/app/examples/card-example/card-example.component.scss
  apps/cookbook/src/app/examples/card-example/card-example.component.ts
  apps/cookbook/src/app/examples/card-example/card-example.module.ts
  apps/cookbook/src/app/examples/card-example/examples/background-image.scss
  apps/cookbook/src/app/examples/card-example/examples/background-image.ts
  apps/cookbook/src/app/examples/card-example/examples/card-background-image-example/card-background-image-example.component.html
  apps/cookbook/src/app/examples/card-example/examples/card-background-image-example/card-background-image-example.component.ts
  apps/cookbook/src/app/examples/card-example/examples/card-clickable-example/card-clickable-example.component.html
  apps/cookbook/src/app/examples/card-example/examples/card-clickable-example/card-clickable-example.component.scss
  apps/cookbook/src/app/examples/card-example/examples/card-clickable-example/card-clickable-example.component.ts
  apps/cookbook/src/app/examples/card-example/examples/card-css-background-image-example/card-css-background-image-example.component.html
  apps/cookbook/src/app/examples/card-example/examples/card-css-background-image-example/card-css-background-image-example.component.ts
  apps/cookbook/src/app/examples/card-example/examples/card-elevations-example/card-elevations-example.component.html
  apps/cookbook/src/app/examples/card-example/examples/card-elevations-example/card-elevations-example.component.scss
  apps/cookbook/src/app/examples/card-example/examples/card-elevations-example/card-elevations-example.component.ts
  apps/cookbook/src/app/examples/card-example/examples/card-example.shared.scss
  apps/cookbook/src/app/examples/card-example/examples/card-themecolor-example/card-themecolor-example.component.html
  apps/cookbook/src/app/examples/card-example/examples/card-themecolor-example/card-themecolor-example.component.scss
  apps/cookbook/src/app/examples/card-example/examples/card-themecolor-example/card-themecolor-example.component.ts
  apps/cookbook/src/app/examples/card-example/examples/card-with-item-header-example/card-with-item-header-example.component.html
  apps/cookbook/src/app/examples/card-example/examples/card-with-item-header-example/card-with-item-header-example.component.ts
  apps/cookbook/src/app/examples/card-example/examples/color.ts
  apps/cookbook/src/app/examples/card-example/examples/default.ts
  apps/cookbook/src/app/examples/card-example/examples/disclosure.ts
  apps/cookbook/src/app/examples/card-example/examples/flag.ts
  apps/cookbook/src/app/showcase/card-showcase/card-showcase.component.html
  apps/cookbook/src/app/showcase/card-showcase/card-showcase.component.scss
Labels: feature

#2792 Remove card mode to align elevation
  apps/cookbook/src/app/examples/card-example/card-example.module.ts
  apps/cookbook/src/app/examples/card-example/examples/flat.ts
  apps/cookbook/src/app/showcase/badge-showcase/badge-showcase.component.html
  apps/cookbook/src/app/showcase/badge-showcase/badge-showcase.component.ts
  apps/cookbook/src/app/showcase/card-showcase/card-showcase.component.html
  apps/cookbook/src/app/showcase/card-showcase/card-showcase.component.ts
  apps/cookbook/src/app/showcase/chart-showcase/chart-showcase.component.html
  apps/cookbook/src/app/showcase/chart-showcase/chart-showcase.component.ts
  apps/cookbook/src/app/showcase/item-sliding-showcase/item-sliding-showcase.component.html
  apps/cookbook/src/app/showcase/item-sliding-showcase/item-sliding-showcase.component.ts
  apps/cookbook/src/app/showcase/stock-chart-showcase/stock-chart-showcase.component.html
  apps/cookbook/src/app/showcase/stock-chart-showcase/stock-chart-showcase.component.ts
  libs/core/src/scss/_global-styles.scss
  libs/core/src/scss/base/_variables.scss
  libs/designsystem/card/src/card.component.scss
  libs/designsystem/card/src/card.component.ts
  libs/designsystem/src/lib/components/button/button.component.scss
  libs/designsystem/src/lib/components/dropdown/dropdown.component.scss
  libs/designsystem/src/lib/components/fab-sheet/fab-sheet.component.scss
  libs/designsystem/src/lib/components/modal/action-sheet/action-sheet.component.scss
  libs/designsystem/src/lib/components/modal/footer/modal-footer.component.scss
Labels: breaking-change

#2796 moved testing-jasmine
  libs/designsystem/testing-jasmine/ng-package.json
  libs/designsystem/testing-jasmine/src/lib/kirby-testing.module.ts
  libs/designsystem/testing-jasmine/src/lib/mock-providers.ts
  libs/designsystem/testing-jasmine/src/public_api.ts
  libs/designsystem/testing-jasmine/src/tsconfig.json
Labels: bug, ignore-for-release

#2704 Emit events when navigating to previous or next month in kirby-calendar
  apps/cookbook/src/app/showcase/calendar-showcase/calendar-showcase.component.ts
  apps/cookbook/src/app/showcase/toggle-button-showcase/toggle-button-showcase.component.ts
  libs/core/src/scss/base/_functions.scss
  libs/designsystem/accordion/ng-package.json
  libs/designsystem/card/ng-package.json
  libs/designsystem/checkbox/ng-package.json
  libs/designsystem/divider/ng-package.json
  libs/designsystem/helpers/ng-package.json
  libs/designsystem/item/ng-package.json
  libs/designsystem/loading-overlay/ng-package.json
  libs/designsystem/popover/ng-package.json
  libs/designsystem/range/ng-package.json
  libs/designsystem/section-header/ng-package.json
  libs/designsystem/shared/ng-package.json
  libs/designsystem/slide-button/ng-package.json
  libs/designsystem/slide/ng-package.json
  libs/designsystem/src/lib/components/calendar/calendar.component.spec.ts
  libs/designsystem/src/lib/components/calendar/calendar.component.ts
  libs/designsystem/testing-base/ng-package.json
  libs/designsystem/testing/ng-package.json
  libs/designsystem/toggle-button/ng-package.json
  libs/designsystem/types/ng-package.json
Labels: feature

#2801 animation as secondary entry
  libs/designsystem/helpers/src/kirby-animation.ts
  libs/designsystem/helpers/src/public_api.ts
  libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.spec.ts
  libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.component.ts
  libs/designsystem/src/lib/components/modal/services/modal-animation-builder.service.ts
  libs/designsystem/src/lib/components/modal/services/modal.controller.ts
  libs/designsystem/src/lib/components/modal/services/modal.helper.ts
  libs/designsystem/src/lib/components/modal/services/modal.interfaces.ts
  libs/designsystem/src/lib/components/page/page.component.ts
  libs/designsystem/src/lib/index.ts
Labels: enhancement, ignore-for-release

#2803 form-field as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/form-field/index.ts
  libs/designsystem/form-field/ng-package.json
  libs/designsystem/form-field/src/_form-field-inputs.shared.scss
  libs/designsystem/form-field/src/directives/affix/affix.directive.ts
  libs/designsystem/form-field/src/directives/date/date-input.directive.spec.ts
  libs/designsystem/form-field/src/directives/date/date-input.directive.ts
  libs/designsystem/form-field/src/directives/decimal-mask/decimal-mask.directive.spec.ts
  libs/designsystem/form-field/src/directives/decimal-mask/decimal-mask.directive.ts
  libs/designsystem/form-field/src/form-field-message/form-field-message.component.html
  libs/designsystem/form-field/src/form-field-message/form-field-message.component.scss
  libs/designsystem/form-field/src/form-field-message/form-field-message.component.ts
  libs/designsystem/form-field/src/form-field.component.html
  libs/designsystem/form-field/src/form-field.component.scss
  libs/designsystem/form-field/src/form-field.component.spec.ts
  libs/designsystem/form-field/src/form-field.component.ts
  libs/designsystem/form-field/src/form-field.module.ts
  libs/designsystem/form-field/src/index.ts
  libs/designsystem/form-field/src/input-counter/input-counter.component.html
  libs/designsystem/form-field/src/input-counter/input-counter.component.spec.ts
  libs/designsystem/form-field/src/input-counter/input-counter.component.ts
  libs/designsystem/form-field/src/input/input.component.integration.spec.ts
  libs/designsystem/form-field/src/input/input.component.scss
  libs/designsystem/form-field/src/input/input.component.spec.ts
  libs/designsystem/form-field/src/input/input.component.ts
  libs/designsystem/form-field/src/public_api.ts
  libs/designsystem/form-field/src/textarea/textarea.component.html
  libs/designsystem/form-field/src/textarea/textarea.component.scss
  libs/designsystem/form-field/src/textarea/textarea.component.spec.ts
  libs/designsystem/form-field/src/textarea/textarea.component.ts
  libs/designsystem/src/lib/components/dropdown/dropdown.module.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2810 Import CommonModule in TextareaComponent
  libs/designsystem/form-field/src/textarea/textarea.component.ts
Labels: ignore-for-release

#2679 Experimental Fullscreen Modal
  apps/cookbook/src/app/app.module.ts
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/modal-example/modal-example.module.ts
  apps/cookbook/src/app/examples/modal-experimental-example/controller/modal-controller-experimental-example.component.html
  apps/cookbook/src/app/examples/modal-experimental-example/controller/modal-controller-experimental-example.component.ts
  apps/cookbook/src/app/examples/modal-experimental-example/fullscreen/fullscreen-experimental-example.component.html
  apps/cookbook/src/app/examples/modal-experimental-example/fullscreen/fullscreen-experimental-example.component.scss
  apps/cookbook/src/app/examples/modal-experimental-example/fullscreen/fullscreen-experimental-example.component.ts
  apps/cookbook/src/app/examples/modal-experimental-example/modal-experimental-example.module.ts
  apps/cookbook/src/app/showcase/modal-experimental-showcase/modal-experimental-showcase.component.html
  apps/cookbook/src/app/showcase/modal-experimental-showcase/modal-experimental-showcase.component.scss
  apps/cookbook/src/app/showcase/modal-experimental-showcase/modal-experimental-showcase.component.ts
  apps/cookbook/src/app/showcase/showcase.common.ts
  apps/cookbook/src/app/showcase/showcase.module.ts
  apps/cookbook/src/app/showcase/showcase.routes.ts
  libs/core/src/scss/_global-styles.scss
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/components/modal-experimental/footer/footer.component.html
  libs/designsystem/src/lib/components/modal-experimental/footer/footer.component.scss
  libs/designsystem/src/lib/components/modal-experimental/footer/footer.component.spec.ts
  libs/designsystem/src/lib/components/modal-experimental/footer/footer.component.ts
  libs/designsystem/src/lib/components/modal-experimental/fullscreen/fullscreen.component.html
  libs/designsystem/src/lib/components/modal-experimental/fullscreen/fullscreen.component.scss
  libs/designsystem/src/lib/components/modal-experimental/fullscreen/fullscreen.component.spec.ts
  libs/designsystem/src/lib/components/modal-experimental/fullscreen/fullscreen.component.ts
  libs/designsystem/src/lib/components/modal-experimental/index.ts
  libs/designsystem/src/lib/components/modal-experimental/services/modal.controller.ts
  libs/designsystem/src/lib/components/modal-experimental/wrapper/wrapper.component.html
  libs/designsystem/src/lib/components/modal-experimental/wrapper/wrapper.component.scss
  libs/designsystem/src/lib/components/modal-experimental/wrapper/wrapper.component.spec.ts
  libs/designsystem/src/lib/components/modal-experimental/wrapper/wrapper.component.ts
  libs/designsystem/src/lib/components/modal/services/modal.controller.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby-modal.module.ts
Labels: feature

#2812 Improve prettier HTML formatting config
  .eslintrc.json
  .prettierrc.json
  apps/cookbook/src/app/examples/list-example/examples/colored-items.ts
  apps/cookbook/src/app/examples/list-example/examples/header-and-footer.ts
  apps/cookbook/src/app/examples/list-example/examples/items-no-dividers.ts
  apps/cookbook/src/app/examples/list-example/examples/items.ts
  apps/cookbook/src/app/examples/list-example/examples/sections-and-colored-items.ts
  apps/cookbook/src/app/examples/list-example/examples/sections-with-standalone.ts
  apps/cookbook/src/app/examples/list-example/examples/sections.ts
  apps/cookbook/src/app/examples/list-example/examples/selectable-items.ts
  apps/cookbook/src/app/examples/list-example/examples/stand-alone.ts
  apps/cookbook/src/app/examples/list-load-on-demand-example/list-load-on-demand-example.component.ts
  apps/cookbook/src/app/examples/tabs-example/tab/tab-example.component.ts
  libs/designsystem/flag/src/flag.component.ts
  libs/designsystem/popover/src/popover.component.ts
  libs/designsystem/src/lib/components/data-table/table-row/table-row.component.ts
  libs/designsystem/src/lib/components/data-table/table/table.component.ts
  libs/designsystem/src/lib/components/modal/modal-wrapper/modal-wrapper.testbuilder.ts
  libs/designsystem/src/lib/components/modal/services/action-sheet.helper.spec.ts
  libs/designsystem/src/lib/components/modal/services/alert.helper.spec.ts
  libs/designsystem/src/lib/components/modal/services/modal.helper.spec.ts
  libs/designsystem/src/lib/components/page/page.component.ts
Labels: housekeeping, ignore-for-release

#2809 Enhancement/avatar progress circle as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/avatar/index.ts
  libs/designsystem/avatar/ng-package.json
  libs/designsystem/avatar/src/avatar.component.html
  libs/designsystem/avatar/src/avatar.component.scss
  libs/designsystem/avatar/src/avatar.component.spec.ts
  libs/designsystem/avatar/src/avatar.component.ts
  libs/designsystem/avatar/src/index.ts
  libs/designsystem/avatar/src/public_api.ts
  libs/designsystem/progress-circle/index.ts
  libs/designsystem/progress-circle/ng-package.json
  libs/designsystem/progress-circle/src/index.ts
  libs/designsystem/progress-circle/src/progress-circle-ring.component.scss
  libs/designsystem/progress-circle/src/progress-circle-ring.component.spec.ts
  libs/designsystem/progress-circle/src/progress-circle-ring.component.svg
  libs/designsystem/progress-circle/src/progress-circle-ring.component.ts
  libs/designsystem/progress-circle/src/progress-circle.component.html
  libs/designsystem/progress-circle/src/progress-circle.component.scss
  libs/designsystem/progress-circle/src/progress-circle.component.spec.ts
  libs/designsystem/progress-circle/src/progress-circle.component.ts
  libs/designsystem/progress-circle/src/public_api.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release

#2815 Enhancement/router outlet as secondary entry
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/router-outlet/index.ts
  libs/designsystem/router-outlet/ng-package.json
  libs/designsystem/router-outlet/src/index.ts
  libs/designsystem/router-outlet/src/public_api.ts
  libs/designsystem/router-outlet/src/router-outlet.component.html
  libs/designsystem/router-outlet/src/router-outlet.component.scss
  libs/designsystem/router-outlet/src/router-outlet.component.spec.ts
  libs/designsystem/router-outlet/src/router-outlet.component.ts
  libs/designsystem/router-outlet/src/router-outlet.module.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: enhancement, ignore-for-release
