Repository kirbydesign/designsystem, pull requests merged in 2023-07, with the labels that each got.

#3157 AutoClose on sliding item when clicking on swipeAction
  libs/designsystem/item-sliding/src/item-sliding.component.html
  libs/designsystem/item-sliding/src/item-sliding.component.spec.ts
  libs/designsystem/item-sliding/src/item-sliding.component.ts
Labels: enhancement, feature

#3143 Redundant code removed that applied already existing styling for divider component
  libs/designsystem/divider/src/divider.component.scss
Labels: housekeeping, ignore-for-release

#3175 Add adjust icon to default icons
  libs/designsystem/icon/src/icons/svg/adjust.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: feature

#3152 Fix sporadically failing tests for kirby-item disclosure animation
  libs/designsystem/item/src/item.component.spec.ts
Labels: fix

#3150 Always show 6 weeks in kirby-calendar to prevent layout shift
  libs/designsystem/calendar/src/calendar.component.scss
  libs/designsystem/calendar/src/calendar.component.spec.ts
  libs/designsystem/calendar/src/calendar.component.ts
Labels: feature

#2859 Fixed autofix lint warnings
  apps/cookbook/src/app/showcase/action-sheet-showcase/action-sheet-showcase.component.ts
  apps/cookbook/src/app/showcase/fab-sheet-showcase/fab-sheet-showcase.component.ts
  apps/cookbook/src/app/showcase/icon-showcase/icon-showcase.component.ts
  apps/cookbook/src/app/showcase/list-load-on-demand-showcase/list-load-on-demand-showcase.component.ts
  apps/cookbook/src/app/showcase/reorder-list-showcase/reorder-list-showcase.component.ts
  apps/cookbook/src/app/showcase/slide-button-showcase/slide-button-showcase.component.ts
  apps/cookbook/src/app/showcase/toast-showcase/toast-showcase.component.ts
  apps/cookbook/src/app/showcase/toggle-showcase/toggle-showcase.component.ts
  package.json
Labels: housekeeping, ignore-for-release

#3153 Prevent tab item de-selection
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.spec.ts
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.ts
Labels: fix

#3180 Disable animations in tests
  libs/designsystem/modal/src/modal/services/action-sheet.helper.spec.ts
  libs/designsystem/modal/src/modal/services/alert.helper.spec.ts
  libs/designsystem/modal/src/modal/services/modal.controller.spec.ts
  libs/designsystem/modal/src/modal/services/modal.helper.spec.ts
  libs/designsystem/testing/src/test-helper.ts
  libs/designsystem/toast/src/services/toast.helper.spec.ts
Labels: ignore-for-release

#3188 Add canDismiss description to the ModalConfig API table
  apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.html
  apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.ts
Labels: documentation, ignore-for-release
