Repository kirbydesign/designsystem, pull requests merged in 2023-05, with the labels that each got.

#3023 Release v8.4.0
  libs/core/package.json
  libs/designsystem/package.json
  package-lock.json
  package.json
Labels: ignore-for-release

#3030 Extend mock base chart for mock charts to work
  libs/designsystem/testing-base/src/lib/components/mock.chart.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.stock-chart.component.ts
Labels: fix

#3031 Release v8.4.1
  package-lock.json
  package.json
Labels: ignore-for-release

#3028 enhancement: add support for progress circle in header
  apps/cookbook/src/app/examples/header-example/examples/progress-circle-with-avatar.ts
  apps/cookbook/src/app/examples/header-example/header-example.component.html
  apps/cookbook/src/app/examples/header-example/header-example.module.ts
  apps/cookbook/src/app/showcase/header-showcase/header-showcase.component.html
  libs/designsystem/header/src/header.component.html
  libs/designsystem/header/src/header.component.spec.ts
  libs/designsystem/header/src/header.component.ts
Labels: feature

#3027 fix: remove hidden title and refactor title and value layout
  libs/designsystem/header/src/header.component.html
  libs/designsystem/header/src/header.component.scss
Labels: fix

#3034 fix: align attentionLevel getter and setter type
  libs/designsystem/button/src/button.component.ts
  package-lock.json
  package.json
Labels: fix

#3035 Enhancement: interactive header title
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/header-example/examples/interactive-title.ts
  apps/cookbook/src/app/showcase/header-showcase/header-showcase.component.html
  apps/cookbook/src/app/showcase/header-showcase/header-showcase.component.ts
  libs/designsystem/header/src/header.component.html
  libs/designsystem/header/src/header.component.scss
  libs/designsystem/header/src/header.component.ts
  libs/designsystem/header/src/header.module.ts
  libs/designsystem/header/src/public_api.ts
  libs/designsystem/page/src/page.component.html
  libs/designsystem/page/src/page.component.scss
  libs/designsystem/page/src/page.component.ts
Labels: feature

#3037 bug: title in a centered key value layout is left aligned
  apps/cookbook/src/app/examples/header-example/examples/combined.ts
  libs/designsystem/header/src/header.component.scss
Labels: fix

#3046 Add new icons
  libs/designsystem/icon/src/icons/svg/feedback.svg
  libs/designsystem/icon/src/icons/svg/keyboard.svg
  libs/designsystem/icon/src/icons/svg/lock.svg
  libs/designsystem/icon/src/icons/svg/overview-outline.svg
  libs/designsystem/icon/src/icons/svg/overview.svg
  libs/designsystem/icon/src/icons/svg/see.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: feature

#3009 Fix FAB sheet backdrop when used in kirby-page
  libs/designsystem/page/src/page.component.scss
Labels: fix

#3048 Release v8.5.0
  libs/core/package.json
  libs/designsystem/package.json
  package.json
Labels: ignore-for-release

#3050 Close modal when clicking the browser back button
  libs/designsystem/modal/src/modal/services/modal.helper.ts
Labels: feature

#3057 Release v8.5.1
  libs/core/package.json
  libs/designsystem/package.json
  package-lock.json
  package.json
Labels: ignore-for-release

#3066 Fix missing highlight of items on keyboard navigation in dropdown when using popover
  libs/designsystem/item/src/item.component.scss
Labels: fix

#3074 Fix missing character count on init when using [(ngModel)] on kirby-input
  libs/designsystem/form-field/src/input-counter/input-counter.component.spec.ts
  libs/designsystem/form-field/src/input/input.component.spec.ts
  libs/designsystem/form-field/src/input/input.component.ts
Labels: fix

#3077 Enhancement: Page should only show toolbar background and divider on desktop when scrolled
  libs/designsystem/page/src/page.component.scss
  libs/designsystem/page/src/page.component.spec.ts
Labels: fix

#3081 Kirby date input shouldn't prefill year
  apps/cookbook/src/app/showcase/form-field-showcase/form-field-showcase.component.html
  apps/cookbook/src/app/showcase/form-field-showcase/form-field-showcase.component.ts
  libs/designsystem/form-field/src/directives/date/date-input.directive.spec.ts
  libs/designsystem/form-field/src/directives/date/date-input.directive.ts
Labels: feature
