Repository kirbydesign/designsystem, pull requests merged in 2023-12, with the labels that each got.

#3304 Segmented Control: fix chip sizing when overflowing horizontally
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.scss
Labels: fix

#3303 Form Field: cannot focus input programmatically immediately after disabled state is removed
  apps/cookbook/src/app/examples/form-field-example/examples/input/focus.ts
  libs/designsystem/form-field/src/form-field.component.spec.ts
  libs/designsystem/form-field/src/form-field.component.ts
Labels: fix

#3258 Toggle: Implement ControlValueAccessor
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/examples/radio-example/examples/reactive-forms.ts
  apps/cookbook/src/app/examples/radio-example/radio-example.module.ts
  apps/cookbook/src/app/examples/reactive-form-state/reactive-form-state.component.html
  apps/cookbook/src/app/examples/reactive-form-state/reactive-form-state.component.ts
  apps/cookbook/src/app/examples/toggle-example/examples/default.ts
  apps/cookbook/src/app/examples/toggle-example/examples/reactive-forms.ts
  apps/cookbook/src/app/examples/toggle-example/toggle-example.component.html
  apps/cookbook/src/app/examples/toggle-example/toggle-example.component.ts
  apps/cookbook/src/app/examples/toggle-example/toggle-example.module.ts
  apps/cookbook/src/app/showcase/toggle-showcase/toggle-showcase.component.html
  apps/cookbook/src/app/showcase/toggle-showcase/toggle-showcase.component.scss
  apps/cookbook/src/app/showcase/toggle-showcase/toggle-showcase.component.ts
  libs/designsystem/toggle/src/toggle.component.spec.ts
  libs/designsystem/toggle/src/toggle.component.ts
Labels: feature

#3310 config: lock date-fns peer dependencies version
  libs/designsystem/package.json
Labels: fix

#3308 Label: Option for multiline - Wrap attribute
  apps/cookbook/src/app/examples/item-example/examples/simple/multiline.ts
  apps/cookbook/src/app/examples/item-example/item-example.module.ts
  apps/cookbook/src/app/examples/section-header-example/examples/heading-with-multiline-label.ts
  apps/cookbook/src/app/examples/section-header-example/section-header-example.component.html
  apps/cookbook/src/app/examples/section-header-example/section-header-example.module.ts
  apps/cookbook/src/app/showcase/item-showcase/item-showcase.component.html
  apps/cookbook/src/app/showcase/section-header-showcase/section-header-showcase.component.html
  libs/core/src/scss/base/_functions.scss
  libs/designsystem/item/src/_item.utils.scss
Labels: feature

#3312 Update Kirby Team
  .github/SUPPORT.md
Labels: ignore-for-release
