Repository kirbydesign/designsystem, pull requests merged in 2023-08, with the labels that each got.

#3192 Release v8.11.0
  package-lock.json
  package.json
Labels: ignore-for-release

#3186 Remove shadow input binding
  libs/designsystem/avatar/src/avatar.component.ts
Labels: breaking-change

#3183 Remove the grid component
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/grid/index.ts
  libs/designsystem/grid/ng-package.json
  libs/designsystem/grid/src/breakpoint-helper.service.ts
  libs/designsystem/grid/src/grid-card-configuration.ts
  libs/designsystem/grid/src/grid.component.html
  libs/designsystem/grid/src/grid.component.scss
  libs/designsystem/grid/src/grid.component.ts
  libs/designsystem/grid/src/index.ts
  libs/designsystem/grid/src/public_api.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/testing-base/src/lib/components/index.ts
  libs/designsystem/testing-base/src/lib/components/mock.grid.component.ts
  libs/designsystem/testing-base/src/lib/mock-components.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: breaking-change

#3178 Remove deprecated methods in modalController
  libs/designsystem/modal/src/modal/services/modal.controller.ts
  libs/designsystem/modal/src/modal/services/modal.helper.ts
  libs/designsystem/testing-jasmine/src/lib/mock-providers.ts
  libs/designsystem/testing-jest/src/lib/mock-providers.ts
Labels: breaking-change

#3170 Remove the registerPresentingElement method in the modal controller & helper
  libs/designsystem/modal/src/modal/services/modal.controller.ts
  libs/designsystem/modal/src/modal/services/modal.helper.ts
  libs/designsystem/testing-jasmine/src/lib/mock-providers.ts
  libs/designsystem/testing-jest/src/lib/mock-providers.ts
Labels: breaking-change

#3166 Remove alert experimental
  apps/cookbook/src/app/examples/alert-experimental-example/alert-experimental-example.component.html
  apps/cookbook/src/app/examples/alert-experimental-example/alert-experimental-example.component.ts
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/showcase/alert-experimental-showcase/alert-experimental-showcase.component.html
  apps/cookbook/src/app/showcase/alert-experimental-showcase/alert-experimental-showcase.component.ts
  apps/cookbook/src/app/showcase/showcase.common.ts
  apps/cookbook/src/app/showcase/showcase.routes.ts
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/alert-experimental/index.ts
  libs/designsystem/alert-experimental/ng-package.json
  libs/designsystem/alert-experimental/src/alert.component.html
  libs/designsystem/alert-experimental/src/alert.component.scss
  libs/designsystem/alert-experimental/src/alert.component.spec.ts
  libs/designsystem/alert-experimental/src/alert.component.ts
  libs/designsystem/alert-experimental/src/alert.module.ts
  libs/designsystem/alert-experimental/src/config/alert-config.ts
  libs/designsystem/alert-experimental/src/index.ts
  libs/designsystem/alert-experimental/src/public_api.ts
  libs/designsystem/alert-experimental/src/services/alert.controller.spec.ts
  libs/designsystem/alert-experimental/src/services/alert.controller.ts
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/src/lib/index.ts
  libs/designsystem/testing-base/src/lib/components/index.ts
  libs/designsystem/testing-base/src/lib/components/mock.alert-experimental.component.ts
  libs/designsystem/testing-base/src/lib/mock-components.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
Labels: breaking-change

#3072 Remove deprecated button attention level 4
  libs/designsystem/button/src/button.component.spec.ts
  libs/designsystem/button/src/button.component.ts
Labels: breaking-change

#3003 Refactor breakpoints map & update kirby-page padding on "sm" breakpoint
  apps/cookbook/src/app/examples/badge-example/badge-example.component.scss
  apps/cookbook/src/app/examples/button-example/button-example.component.scss
  apps/cookbook/src/app/examples/dropdown-example/examples/dropdown-examples.shared.scss
  apps/cookbook/src/app/examples/list-no-shape-example/list-no-shape-example.component.scss
  apps/cookbook/src/app/showcase/grid-showcase/grid-showcase.component.html
  libs/core/src/scss/base/_variables.scss
  libs/core/src/scss/components/_grid.scss
  libs/designsystem/dropdown/src/dropdown.component.scss
  libs/designsystem/modal/src/modal/action-sheet/action-sheet.component.scss
  libs/designsystem/modal/src/modal/alert/alert.component.scss
  libs/designsystem/page/src/page.component.scss
  libs/designsystem/slide/src/slides.component.ts
Labels: breaking-change

#3155 Fix resize handler in safari browser
  libs/designsystem/form-field/src/textarea/textarea.component.scss
Labels: fix

#3202 Tab Button: properly remove active state when icon is click target
  libs/designsystem/icon/src/icon.component.scss
Labels: fix

#3176 Migration notes Kirby v9
  MIGRATION.md
Labels: ignore-for-release

#2979 Make 'standard' the default maxWidth option for Page
  MIGRATION.md
  apps/cookbook/src/app/examples/page-example/content-width/page-content-width-example.component.ts
  apps/cookbook/src/app/showcase/page-showcase/page-showcase.component.ts
  libs/core/src/helpers/design-token-helper.ts
  libs/core/src/scss/base/_functions.scss
  libs/core/src/scss/base/_variables.scss
  libs/designsystem/page/src/page-footer/page-footer.component.scss
  libs/designsystem/page/src/page.component.scss
  libs/designsystem/page/src/page.component.spec.ts
  libs/designsystem/page/src/page.component.ts
  libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.scss
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.scss
Labels: enhancement

#3218 Add new icons to kirby
  libs/designsystem/icon/src/icons/svg/bs-logo.svg
  libs/designsystem/icon/src/icons/svg/company.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: enhancement

#3219 Github: fix broken links in issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/component-request.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
Labels: ignore-for-release
