Repository kirbydesign/designsystem, pull requests merged in 2023-03, with the labels that each got.

#2906 Fix ion-backdrop scroll block on navigation return
  libs/designsystem/fab-sheet/src/fab-sheet.component.ts
Labels: bug

#2889 Desktop ready modal
  libs/core/src/scss/_global-styles.scss
  libs/core/src/scss/base/_variables.scss
  libs/designsystem/modal/experimental/src/footer/footer.component.html
  libs/designsystem/modal/experimental/src/footer/footer.component.scss
  libs/designsystem/modal/experimental/src/footer/footer.component.spec.ts
  libs/designsystem/modal/experimental/src/modal/modal.component.html
  libs/designsystem/modal/experimental/src/modal/modal.component.scss
  libs/designsystem/modal/experimental/src/modal/modal.component.ts
  libs/designsystem/modal/experimental/src/services/modal.controller.ts
  libs/designsystem/modal/experimental/src/wrapper/wrapper.component.html
  libs/designsystem/modal/experimental/src/wrapper/wrapper.component.scss
  libs/designsystem/modal/experimental/src/wrapper/wrapper.component.ts
Labels: feature

#2912 Revert "[KirbyPage] Fix rare title intersection observer bug (#2822)"
  libs/designsystem/page/src/page.component.ts
Labels: fix

#2915 [Enhancement] Add support for setting `showIconOnly` on Button
  apps/cookbook/src/app/examples/button-example/button-example.component.html
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/button/src/button.component.spec.ts
  libs/designsystem/button/src/button.component.ts
Labels: feature

#2904 New Drawer modal
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/modal-experimental-example/controller/modal-controller-experimental-example.component.html
  apps/cookbook/src/app/examples/modal-experimental-example/modal-experimental-example.module.ts
  apps/cookbook/src/app/examples/modal-experimental-example/modal/drawer/drawer-experimental-example.component.html
  apps/cookbook/src/app/examples/modal-experimental-example/modal/drawer/drawer-experimental-example.component.scss
  apps/cookbook/src/app/examples/modal-experimental-example/modal/drawer/drawer-experimental-example.component.ts
  apps/cookbook/src/app/examples/modal-experimental-example/modal/fullscreen/fullscreen-experimental-example.component.html
  apps/cookbook/src/app/examples/modal-experimental-example/modal/fullscreen/fullscreen-experimental-example.component.scss
  apps/cookbook/src/app/examples/modal-experimental-example/modal/fullscreen/fullscreen-experimental-example.component.ts
  apps/cookbook/src/app/examples/modal-experimental-example/nested-modals/nested-modals-experimental-example.component.html
  apps/cookbook/src/app/examples/modal-experimental-example/nested-modals/nested-modals-experimental-example.component.scss
  apps/cookbook/src/app/examples/modal-experimental-example/nested-modals/nested-modals-experimental-example.component.ts
  apps/cookbook/src/app/showcase/modal-experimental-showcase/modal-experimental-showcase.component.html
  apps/cookbook/src/app/showcase/modal-experimental-showcase/modal-experimental-showcase.component.ts
  libs/core/src/scss/_global-styles.scss
  libs/designsystem/modal/experimental/src/modal/modal.component.html
  libs/designsystem/modal/experimental/src/modal/modal.component.spec.ts
  libs/designsystem/modal/experimental/src/modal/modal.component.ts
  libs/designsystem/modal/experimental/src/services/modal.controller.ts
  libs/designsystem/modal/experimental/src/wrapper/wrapper.component.html
  libs/designsystem/modal/experimental/src/wrapper/wrapper.component.ts
Labels: feature

#2922 Fix item disabled still clickable
  libs/designsystem/item/src/item.component.scss
  libs/designsystem/item/src/item.component.spec.ts
  libs/designsystem/item/src/item.component.ts
Labels: fix

#2927 Fix/2921 progress circle not showing themecolor
  libs/designsystem/progress-circle/src/progress-circle-ring.component.ts
  libs/designsystem/progress-circle/src/progress-circle.component.spec.ts
  libs/designsystem/progress-circle/src/progress-circle.component.ts
Labels: fix

#2907 Fix setting disclosure input to null in kirby-item
  apps/cookbook/src/app/showcase/item-showcase/item-showcase.component.ts
  libs/designsystem/item/src/item.component.spec.ts
  libs/designsystem/item/src/item.component.ts
Labels: component:Item, fix

#2929 Hotfix Release v8.1.4: Toolbar flicker, Progress circle theme-color, Disabled item clickable
  libs/core/package.json
  libs/designsystem/package.json
  package-lock.json
  package.json
Labels: ignore-for-release

#2897 Add x-small button size
  apps/cookbook/src/app/examples/button-example/button-example.component.html
  apps/cookbook/src/app/examples/button-example/button-example.component.ts
  apps/cookbook/src/app/showcase/button-showcase/button-showcase.component.ts
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/button/src/button.component.spec.ts
  libs/designsystem/button/src/button.component.ts
Labels: enhancement

#2937 Add new breakpoints and reuse in Grid & Page
  libs/core/src/scss/base/_variables.scss
  libs/core/src/scss/components/_grid.scss
  libs/designsystem/page/src/page.component.scss
Labels: enhancement

#2936 Enhancement/2935 implement roving tabindex and accessibility patterns
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.html
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.scss
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.spec.ts
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.ts
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.html
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.scss
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.spec.ts
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.ts
Labels: enhancement

#2941 Fix excess change-detection cycles on page scroll
  libs/designsystem/page/src/page.component.ts
Labels: fix

#2943 Add box shadow to buttons with attention level 3
  libs/designsystem/button/src/button.component.integration.spec.ts
  libs/designsystem/button/src/button.component.scss
Labels: feature

#2750 Enhancement/2705 kirby component from experimental local navigation
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/page-example/tab-navigation/page-tab-nav-example.component.ts
  apps/cookbook/src/app/showcase/page-showcase/page-showcase.component.html
  apps/cookbook/src/app/showcase/page-showcase/page-showcase.component.ts
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/designsystem/dropdown/src/dropdown.component.ts
  libs/designsystem/dropdown/src/keyboard-handler.service.ts
  libs/designsystem/page/src/page.component.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tab-navigation/index.ts
  libs/designsystem/tab-navigation/ng-package.json
  libs/designsystem/tab-navigation/src/index.ts
  libs/designsystem/tab-navigation/src/public_api.ts
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.html
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.scss
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.spec.ts
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.ts
  libs/designsystem/tab-navigation/src/tab-navigation.module.ts
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.html
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.scss
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.spec.ts
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
  package-lock.json
Labels: enhancement, feature

#2961 Add Modal V2 to KirbyModule
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
Labels: feature

#2959 Add box shadow to buttons with attention level 3
  libs/core/src/scss/themes/_component-themes.scss
  libs/designsystem/button/src/button.component.scss
Labels: feature

#2931 Add support for Header in Page
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/header-example/examples/action-group.ts
  apps/cookbook/src/app/examples/header-example/examples/avatar.ts
  apps/cookbook/src/app/examples/header-example/examples/combined.ts
  apps/cookbook/src/app/examples/header-example/examples/custom-section.ts
  apps/cookbook/src/app/examples/header-example/examples/default.ts
  apps/cookbook/src/app/examples/header-example/examples/flag.ts
  apps/cookbook/src/app/examples/header-example/examples/title-scaling.ts
  apps/cookbook/src/app/examples/header-example/examples/value.ts
  apps/cookbook/src/app/examples/header-example/header-example.component.html
  apps/cookbook/src/app/examples/header-example/header-example.module.ts
  apps/cookbook/src/app/iphone/iphone.component.html
  apps/cookbook/src/app/iphone/iphone.component.scss
  apps/cookbook/src/app/iphone/iphone.component.ts
  apps/cookbook/src/app/iphone/iphone.module.ts
  apps/cookbook/src/app/showcase/header-showcase/header-showcase.component.html
  apps/cookbook/src/app/showcase/header-showcase/header-showcase.component.ts
  apps/cookbook/src/app/showcase/page-showcase/page-showcase.component.html
  apps/cookbook/src/app/showcase/page-showcase/page-showcase.component.scss
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/core/package.json
  libs/designsystem/action-group/index.ts
  libs/designsystem/action-group/ng-package.json
  libs/designsystem/action-group/src/action-group.component.html
  libs/designsystem/action-group/src/action-group.component.scss
  libs/designsystem/action-group/src/action-group.component.ts
  libs/designsystem/action-group/src/index.ts
  libs/designsystem/action-group/src/public_api.ts
  libs/designsystem/button/src/button.component.integration.spec.ts
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/button/src/button.component.spec.ts
  libs/designsystem/button/src/button.component.ts
  libs/designsystem/dropdown/src/dropdown.component.html
  libs/designsystem/dropdown/src/dropdown.component.scss
  libs/designsystem/dropdown/src/dropdown.component.ts
  libs/designsystem/header/src/header.component.html
  libs/designsystem/header/src/header.component.scss
  libs/designsystem/header/src/header.component.spec.ts
  libs/designsystem/header/src/header.component.ts
  libs/designsystem/header/src/header.module.ts
  libs/designsystem/header/src/public_api.ts
  libs/designsystem/item/src/item.component.scss
  libs/designsystem/package.json
  libs/designsystem/page/src/page.component.html
  libs/designsystem/page/src/page.component.scss
  libs/designsystem/page/src/page.component.ts
  libs/designsystem/page/src/page.module.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
  package-lock.json
  package.json
Labels: feature

#2966 PageBackButtonOverride as Interface
  apps/cookbook/src/app/showcase/page-showcase/page-showcase.component.html
  apps/cookbook/src/app/showcase/page-showcase/page-showcase.component.ts
  libs/designsystem/page/src/page.component.ts
Labels: feature

#2967 Fix missing dependency for portal directive and mismatch in reference getter/setter types
  libs/designsystem/ng-package.json
  libs/designsystem/package.json
  libs/designsystem/shared/floating/src/floating.directive.ts
  package-lock.json
  package.json
Labels: fix
