Repository kirbydesign/designsystem, pull requests merged in 2023-09, with the labels that each got.

#3214 Slides: remove selectedSlide event emitter
  MIGRATION.md
  apps/cookbook/src/app/showcase/slides-showcase/slides-showcase.component.ts
  libs/designsystem/slide/src/slides.component.spec.ts
  libs/designsystem/slide/src/slides.component.ts
Labels: breaking-change

#3213 Slides: change showNavigation default to true
  MIGRATION.md
  apps/cookbook/src/app/showcase/slides-showcase/slides-showcase.component.ts
  libs/designsystem/slide/src/slides.component.ts
Labels: breaking-change

#3154 Add active interaction state for selectable rows in kirby-table
  libs/core/src/scss/base/_html-table.scss
Labels: feature

#3212 Form Field: add option to reserve space for message
  apps/cookbook/src/app/showcase/form-field-showcase/form-field-showcase.component.ts
  libs/designsystem/form-field/src/form-field-message/form-field-message.component.scss
  libs/designsystem/form-field/src/form-field.component.html
  libs/designsystem/form-field/src/form-field.component.spec.ts
  libs/designsystem/form-field/src/form-field.component.ts
Labels: feature

#3207 Add missing deprecation warnings for legacy Page Actions and Local Navigation
  libs/designsystem/page/src/page.component.ts
  libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.ts
Labels: ignore-for-release

#3226 Input: fix layout shift when hasError is changed from false to true
  libs/designsystem/form-field/src/input/input.component.scss
  libs/designsystem/form-field/src/input/input.component.spec.ts
Labels: fix

#3194 Clean up warning logs in test suites
  libs/designsystem/button/src/button.component.integration.spec.ts
  libs/designsystem/card/src/card-as-button/card-as-button.directive.spec.ts
  libs/designsystem/checkbox/src/checkbox.component.integration.spec.ts
  libs/designsystem/dropdown/src/dropdown-popover.component.integration.spec.ts
  libs/designsystem/dropdown/src/dropdown-popover.component.spec.ts
  libs/designsystem/dropdown/src/dropdown.component.spec.ts
  libs/designsystem/empty-state/src/empty-state.component.integration.spec.ts
  libs/designsystem/header/src/header.component.spec.ts
  libs/designsystem/item-sliding/src/item-sliding.component.spec.ts
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.integration.spec.ts
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.spec.ts
  libs/designsystem/modal/src/modal/alert/alert.component.spec.ts
  libs/designsystem/modal/v2/src/wrapper/wrapper.component.spec.ts
Labels: housekeeping, ignore-for-release

#3230 Build: remove legacy webpack css import notation
  libs/core/src/scss/base/_ionic.scss
  libs/core/src/scss/base/_typography.scss
  libs/core/stencil.config.ts
Labels: fix

#3229 Dependencies: Cap swiper peer-dependency to specific major version
  libs/designsystem/package.json
Labels: fix

#3228 Docs: Use DesignTokenHelper for "breakpoints" map values in docs
  apps/cookbook/src/app/showcase/grid-showcase/grid-showcase.component.html
  apps/cookbook/src/app/showcase/grid-showcase/grid-showcase.component.ts
Labels: ignore-for-release

#3238 Calendar: Remove hover effect on disabled days
  libs/designsystem/calendar/src/calendar.component.scss
Labels: feature

#3231 Header: add support for subtitle1 and subtitle2 as string arrays
  apps/cookbook/src/app/examples/header-example/examples/subtitles.ts
  apps/cookbook/src/app/examples/header-example/header-example.component.html
  apps/cookbook/src/app/examples/header-example/header-example.module.ts
  apps/cookbook/src/app/showcase/header-showcase/header-showcase.component.html
  libs/designsystem/header/src/header.component.html
  libs/designsystem/header/src/header.component.scss
  libs/designsystem/header/src/header.component.spec.ts
  libs/designsystem/header/src/header.component.ts
Labels: feature

#3172 Icon: Use IconRegistry for builtin icon logic and deprecate customName
  libs/designsystem/icon/src/icon-registry.service.spec.ts
  libs/designsystem/icon/src/icon-registry.service.ts
  libs/designsystem/icon/src/icon.component.spec.ts
  libs/designsystem/icon/src/icon.component.ts
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.html
Labels: feature
