Repository kirbydesign/designsystem, pull requests merged in 2023-10, with the labels that each got.

#3263 Dependencies: Remove stencil and reintroduce badge as Angular component
  apps/cookbook/tsconfig.json
  apps/flows/tsconfig.json
  libs/core/package.json
  libs/core/src/components/badge/badge.component.tsx
  libs/core/src/components/badge/badge.types.ts
  libs/core/src/components/badge/readme.md
  libs/core/src/index.ts
  libs/core/stencil.config.ts
  libs/core/tsconfig.json
  libs/designsystem/badge/index.ts
  libs/designsystem/badge/ng-package.json
  libs/designsystem/badge/src/badge.component.html
  libs/designsystem/badge/src/badge.component.scss
  libs/designsystem/badge/src/badge.component.spec.ts
  libs/designsystem/badge/src/badge.component.ts
  libs/designsystem/badge/src/index.ts
  libs/designsystem/badge/src/public_api.ts
  libs/designsystem/helpers/src/string-helper.spec.ts
  libs/designsystem/shared/src/theme-color/theme-color.directive.ts
  libs/designsystem/src/lib/components/angular-component-lib/utils.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/components/kirby-badge.module.ts
  libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.ts
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts
  libs/designsystem/src/lib/components/web-component-proxies.component.ts
  libs/designsystem/src/lib/custom-elements-initializer.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.spec.ts
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.spec.ts
  libs/designsystem/testing-base/src/lib/components/index.ts
  libs/designsystem/testing-base/src/lib/components/mock.badge.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.web-component-proxies.component.ts
  libs/designsystem/testing-base/src/lib/mock-components.ts
  libs/designsystem/tsconfig.json
  libs/designsystem/tsconfig.spec.json
  package-lock.json
  package.json
  scripts/publish.js
  tools/generate-mocks/generate-mocks.ts
Labels: ignore-for-release

#3266 Docs: Fix typo
  apps/cookbook/src/app/examples/grid-example/grid-example.component.html
Labels: housekeeping, documentation, ignore-for-release

#3264 Dependencies: Upgrade to Angular 16
  .eslintignore
  .eslintrc.json
  .github/actions/kirby-setup/action.yml
  angular.json
  apps/cookbook/.eslintrc.json
  apps/cookbook/project.json
  apps/flows/.eslintrc.json
  apps/flows/project.json
  decorate-angular-cli.js
  libs/designsystem/.eslintrc.json
  libs/designsystem/form-field/src/directives/date/date-input.directive.spec.ts
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts
  libs/designsystem/modal/src/modal/action-sheet/action-sheet.component.spec.ts
  libs/designsystem/package.json
  libs/designsystem/page/src/page.component.ts
  libs/designsystem/project.json
  libs/designsystem/radio/src/radio-group/radio-group.component.ts
  libs/designsystem/shared/floating/src/floating.directive.spec.ts
  nx.json
  package-lock.json
  package.json
  project.json
  scripts/sass-extract-to-ts.js
  tools/generate-mocks/tsconfig.json
  tools/generators/.gitkeep
  tools/sass-to-ts/tsconfig.json
Labels: dependencies

#3273 Docs: Fix github example link in cookbook showcases
  apps/cookbook/src/app/showcase/showcase.component.ts
Labels: ignore-for-release

#2777 Component overview update SVGs and text
  apps/cookbook/src/app/component-overview/component-configuration.json
  apps/cookbook/src/assets/component-svg/Alert-Kirby-Component-Overview.svg
  apps/cookbook/src/assets/component-svg/Calendar-Kirby-Component-Overview.svg
  apps/cookbook/src/assets/component-svg/Checkbox-Kirby-Component-Overview.svg
  apps/cookbook/src/assets/component-svg/Header-Kirby-Component-Overview.svg
  apps/cookbook/src/assets/component-svg/Menu-Kirby-Component-Overview.svg
  apps/cookbook/src/assets/component-svg/Radio-Buttons-Kirby-Component-Overview.svg
  apps/cookbook/src/assets/component-svg/Range-Slider-Kirby-Component-Overview.svg
  apps/cookbook/src/assets/component-svg/Spinner-Kirby-Component-Overview.svg
  apps/cookbook/src/assets/component-svg/Toggle-Kirby-Component-Overview.svg
Labels: enhancement
