Repository kirbydesign/designsystem, pull requests merged in 2023-06, with the labels that each got.

#3019 Revert "added warning about missing directive declaration"
  apps/cookbook/src/app/showcase/form-field-showcase/form-field-showcase.component.html
Labels: ignore-for-release

#3008 Changed DateInputDirective declaration
  libs/designsystem/form-field/src/directives/date/date-input.directive.ts
  libs/designsystem/form-field/src/input/input.component.ts
Labels: fix

#2949 New Kirby Slides design
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/slides-example/slides-advanced-example/slides-advanced-example.component.html
  apps/cookbook/src/app/examples/slides-example/slides-advanced-example/slides-advanced-example.component.ts
  apps/cookbook/src/app/examples/slides-example/slides-code-snippets.ts
  apps/cookbook/src/app/examples/slides-example/slides-example.component.ts
  apps/cookbook/src/app/examples/slides-example/slides-example.shared.scss
  apps/cookbook/src/app/examples/slides-example/slides-simple-example/slides-simple-example.component.html
  apps/cookbook/src/app/examples/slides-example/slides-simple-example/slides-simple-example.component.ts
  apps/cookbook/src/app/showcase/slides-showcase/slides-showcase.component.html
  apps/cookbook/src/app/showcase/slides-showcase/slides-showcase.component.ts
  libs/designsystem/card/src/card.component.scss
  libs/designsystem/slide/src/public_api.ts
  libs/designsystem/slide/src/slide.module.ts
  libs/designsystem/slide/src/slides.component.html
  libs/designsystem/slide/src/slides.component.scss
  libs/designsystem/slide/src/slides.component.spec.ts
  libs/designsystem/slide/src/slides.component.ts
  package-lock.json
  package.json
Labels: feature

#3101 Action Group: Render changes to `visibleActions`
  libs/designsystem/action-group/src/action-group.component.ts
Labels: fix

#3103 Fix too large click area for extra small button
  apps/cookbook/src/app/examples/button-example/button-example.component.html
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/button/src/button.component.spec.ts
Labels: fix

#3095 Pass ModalConfig to modal via route data
  apps/cookbook/src/app/examples/dropdown-example/examples/dropdown-examples.shared.scss
  apps/cookbook/src/app/examples/example-configuration-wrapper/example-configuration-wrapper.component.scss
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/modal-example/modal-example-configuration/modal-example-configuration.component.html
  apps/cookbook/src/app/examples/modal-example/modal-example-configuration/modal-example-configuration.component.scss
  apps/cookbook/src/app/examples/modal-example/modal-example-outlet.component.scss
  apps/cookbook/src/app/examples/modal-example/modal-example-outlet.component.ts
  apps/cookbook/src/app/showcase/item-showcase/item-showcase.component.scss
  apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.html
  apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.ts
  apps/cookbook/src/app/showcase/showcase.routes.ts
  apps/cookbook/src/styles.scss
  libs/core/src/scss/base/_link.scss
  libs/designsystem/modal/src/modal-wrapper/config/modal-config.ts
  libs/designsystem/modal/src/modal/services/modal.controller.ts
  libs/designsystem/src/lib/directives/modal-router-link/modal-router-link.directive.ts
Labels: feature

#3107 Add swiper peer dependency
  libs/designsystem/package.json
Labels: fix

#3106 Replace Dropdown with Menu in Action Group
  libs/designsystem/action-group/src/action-group.component.html
  libs/designsystem/action-group/src/action-group.component.scss
  libs/designsystem/action-group/src/action-group.component.ts
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/dropdown/src/dropdown.component.html
  libs/designsystem/dropdown/src/dropdown.component.scss
  libs/designsystem/dropdown/src/dropdown.component.ts
  libs/designsystem/menu/src/menu.component.html
  libs/designsystem/menu/src/menu.component.ts
  libs/designsystem/shared/floating/src/floating.directive.ts
  libs/designsystem/testing-base/src/lib/components/mock.dropdown.component.ts
  libs/designsystem/types/src/event-listener-dispose-fn.ts
  libs/designsystem/types/src/public_api.ts
Labels: fix

#3111 Page: add option to subscribe to toolbar title click
  libs/designsystem/header/src/header.component.html
  libs/designsystem/header/src/header.component.ts
  libs/designsystem/page/src/page.component.ts
Labels: feature

#3116 Disable animations on desktop
  libs/designsystem/router-outlet/src/router-outlet.component.html
  libs/designsystem/router-outlet/src/router-outlet.component.ts
Labels: feature

#3118 Only warn once about table deprecations
  libs/designsystem/data-table/src/table-row/table-row.component.ts
Labels: fix

#3073 Visual adjustments for header, toolbar and action buttons + add missing tests for header and action group components
  apps/cookbook/src/app/examples/page-example/advanced/page-custom-title-example.component.ts
  libs/designsystem/action-group/src/action-group.component.scss
  libs/designsystem/action-group/src/action-group.component.spec.ts
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/header/src/header.component.scss
  libs/designsystem/header/src/header.component.spec.ts
  libs/designsystem/page/src/page.component.html
  libs/designsystem/page/src/page.component.scss
  libs/designsystem/page/src/page.component.spec.ts
  libs/designsystem/page/src/page.component.ts
Labels: fix

#3061 Refactor the solution to show an alert before closing the modal
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/modal-example/alert-example/modal-example-embedded-alert.component.ts
  apps/cookbook/src/app/examples/modal-example/embedded-modal-example/embedded-modal-example.component.html
  apps/cookbook/src/app/examples/modal-example/embedded-modal-example/embedded-modal-example.component.ts
  apps/cookbook/src/app/examples/modal-example/modal-example-advanced.component.ts
  apps/cookbook/src/app/examples/modal-example/modal-example-alert.component.ts
  apps/cookbook/src/app/examples/modal-example/modal-example.module.ts
  apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.html
  apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.ts
  libs/designsystem/modal/src/modal-wrapper/compact/modal-compact-wrapper.component.ts
  libs/designsystem/modal/src/modal-wrapper/config/modal-config.ts
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.integration.spec.ts
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.spec.ts
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts
  libs/designsystem/modal/src/modal.interfaces.ts
  libs/designsystem/modal/src/modal/services/can-dismiss.helper.spec.ts
  libs/designsystem/modal/src/modal/services/can-dismiss.helper.ts
  libs/designsystem/modal/src/modal/services/index.ts
  libs/designsystem/modal/src/modal/services/modal.helper.spec.ts
  libs/designsystem/modal/src/modal/services/modal.helper.ts
  libs/designsystem/src/lib/kirby.module.ts
Labels: fix

#3126 Update tabs navigation layout to new design spec
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/page-example/fixed-footer-tabs/fixed-footer-tabs-example.component.ts
  apps/cookbook/src/app/examples/tabs-example/tab/tab-example-menu.component.ts
  apps/cookbook/src/app/examples/tabs-example/tab/tab-example.component.ts
  apps/cookbook/src/app/examples/tabs-example/tabs-example.component.html
  apps/cookbook/src/app/examples/tabs-example/tabs-example.component.ts
  libs/designsystem/icon/src/icons/svg/menu-no-decoration.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
  libs/designsystem/modal/src/modal/services/modal.helper.spec.ts
  libs/designsystem/page/src/page.component.ts
  libs/designsystem/tabs/src/tab-button/tab-button.component.html
  libs/designsystem/tabs/src/tab-button/tab-button.component.scss
  libs/designsystem/tabs/src/tab-button/tab-button.component.spec.ts
  libs/designsystem/tabs/src/tabs.component.scss
  libs/designsystem/tabs/src/tabs.component.spec.ts
Labels: fix

#3128 Ensure correct spacing on page actions buttons
  libs/designsystem/page/src/page.component.spec.ts
  libs/designsystem/page/src/page.component.ts
Labels: fix

#3129 Remove obsolete Ionic shims
  libs/designsystem/kirby-ionic-module/src/kirby-ionic.module.ts
Labels: fix

#3131 Revert sass.math removal
  libs/designsystem/tabs/src/tab-button/tab-button.component.scss
Labels: fix

#3139 Tabs: only apply animation to background-color
  libs/designsystem/tabs/src/tab-button/tab-button.component.scss
  libs/designsystem/tabs/src/tab-button/tab-button.component.spec.ts
Labels: fix

#3142 Add list and grid svg icons
  libs/designsystem/icon/src/icons/svg/grid.svg
  libs/designsystem/icon/src/icons/svg/list.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: enhancement

#3125 Add animation on disclosure icon
  apps/cookbook/src/app/examples/item-example/examples/disclosure-animation.ts
  apps/cookbook/src/app/examples/item-example/item-example.module.ts
  apps/cookbook/src/app/showcase/item-showcase/item-showcase.component.html
  apps/cookbook/src/app/showcase/item-showcase/item-showcase.component.scss
  apps/cookbook/src/app/showcase/item-showcase/item-showcase.component.ts
  libs/designsystem/item/src/item.component.html
  libs/designsystem/item/src/item.component.scss
  libs/designsystem/item/src/item.component.spec.ts
  libs/designsystem/item/src/item.component.ts
Labels: feature

#3146 Toolbar: fix text overflow when using interactive title
  libs/designsystem/page/src/page.component.html
  libs/designsystem/page/src/page.component.scss
Labels: fix
