Repository kirbydesign/designsystem, pull requests merged in 2024-01, with the labels that each got.

#3318 Icon: Add budget and history icons
  libs/designsystem/icon/src/icons/svg/budget.svg
  libs/designsystem/icon/src/icons/svg/history.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: feature

#3322 Icon: Add new dot icon
  libs/designsystem/icon/src/icons/svg/dot.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: feature

#3323 🙈 Ignore .nx directory
  .gitignore
Labels: housekeeping, ignore-for-release

#3331 Icon: Add agreement icon
  libs/designsystem/icon/src/icons/svg/agreement.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: feature

#3326 Tab Navigation: Fix width on narrow screens
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.scss
Labels: fix

#3327 Styles: align elevation styles for code and design
  apps/cookbook/src/app/examples/badge-example/examples/badge-example-shared.scss
  apps/cookbook/src/app/showcase/badge-showcase/badge-showcase.component.html
  apps/cookbook/src/app/showcase/badge-showcase/badge-showcase.component.ts
  libs/core/src/scss/_global-styles.scss
  libs/core/src/scss/base/_variables.scss
  libs/designsystem/avatar/src/avatar.component.scss
  libs/designsystem/badge/src/badge.component.scss
  libs/designsystem/badge/src/badge.component.spec.ts
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/modal/src/modal/action-sheet/action-sheet.component.scss
  libs/designsystem/modal/src/modal/footer/modal-footer.component.scss
  libs/designsystem/radio/src/radio.component.scss
  libs/designsystem/radio/src/radio.component.spec.ts
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.scss
Labels: fix

#3325 Modal: Move focus to overlay when modal is opened
  apps/cookbook/src/app/examples/example-configuration-wrapper/example-configuration-wrapper.component.scss
  libs/designsystem/modal/src/modal/services/modal.helper.ts
Labels: fix

#3333 Fonts: New heading style h4
  apps/cookbook/src/app/showcase/fonts-showcase/fonts-showcase.component.html
  apps/cookbook/src/app/showcase/fonts-showcase/fonts-showcase.component.scss
  libs/core/src/scss/base/_typography.scss
  libs/designsystem/helpers/scss/src/typography.spec.ts
Labels: feature

#3338 Input: fix initial value not shown in Chrome
  apps/cookbook/src/app/showcase/form-field-showcase/form-field-showcase.component.html
  libs/designsystem/form-field/src/directives/date/date-input.directive.spec.ts
  libs/designsystem/form-field/src/directives/date/date-input.directive.ts
Labels: fix

#3344 Release v9.1.0
  libs/core/package.json
  libs/designsystem/package.json
  package.json
Labels: ignore-for-release
