Repository kirbydesign/designsystem, pull requests merged in 2024-12, with the labels that each got.

#3717 Accessibility: translate internal component labels
  apps/cookbook/src/app/app.routes.ts
  apps/cookbook/src/app/localization/locale-provider/da-locale-provider.component.ts
  apps/cookbook/src/app/localization/locale-provider/en-locale-provider.component.ts
  apps/cookbook/src/app/localization/localization.component.html
  apps/cookbook/src/app/localization/localization.component.scss
  apps/cookbook/src/app/localization/localization.component.ts
  apps/cookbook/src/assets/images/dk.svg
  apps/cookbook/src/assets/images/gb.svg
  libs/designsystem/calendar/src/calendar.component.html
  libs/designsystem/calendar/src/calendar.component.ts
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.html
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts
  libs/designsystem/page/src/page.component.html
  libs/designsystem/page/src/page.component.ts
  libs/designsystem/shared/src/public_api.ts
  libs/designsystem/shared/src/translation/translation.interface.ts
  libs/designsystem/shared/src/translation/translation.service.spec.ts
  libs/designsystem/shared/src/translation/translation.service.ts
  libs/designsystem/shared/src/translation/translations/da.ts
  libs/designsystem/shared/src/translation/translations/en.ts
  libs/designsystem/slide/src/slides.component.ts
Labels: feature

#3731 Housekeeping: Create Cookbook example story for Form Field
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/form-field-example/form-field-example.component.html
  apps/cookbook/src/app/examples/form-field-example/form-field-example.module.ts
  libs/designsystem/form-field/src/form-field.component.stories.ts
  libs/designsystem/form-field/src/form-field.module.ts
Labels: ignore-for-release

#3702 Modal, Alert: label modal with title contents
  apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html
  apps/cookbook/src/app/showcase/empty-state-showcase/empty-state-showcase.component.html
  apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.html
  apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.ts
  libs/designsystem/empty-state/src/empty-state.component.html
  libs/designsystem/empty-state/src/empty-state.component.scss
  libs/designsystem/empty-state/src/empty-state.component.ts
  libs/designsystem/helpers/src/content-mutation-observer.spec.ts
  libs/designsystem/helpers/src/content-mutation-observer.ts
  libs/designsystem/helpers/src/element-ancestor-utils.ts
  libs/designsystem/helpers/src/public_api.ts
  libs/designsystem/modal/src/modal-wrapper/compact/modal-compact-wrapper.component.ts
  libs/designsystem/modal/src/modal-wrapper/config/modal-config.ts
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.integration.spec.ts
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts
  libs/designsystem/modal/src/modal/modal-component/modal.component.ts
  libs/designsystem/modal/src/modal/services/alert.helper.spec.ts
  libs/designsystem/modal/src/modal/services/modal.helper.spec.ts
  libs/designsystem/modal/src/modal/services/modal.helper.ts
  libs/designsystem/testing/src/test-helper.ts
  libs/designsystem/types/src/public_api.ts
  libs/designsystem/types/src/unobserve-fn.ts
Labels: feature

#3703 Menu: enable keyboard interaction and improve semantics
  apps/cookbook/src/app/examples/menu-example/examples/advanced.ts
  apps/cookbook/src/app/examples/menu-example/examples/customButton.ts
  apps/cookbook/src/app/examples/menu-example/examples/customPlacement.ts
  apps/cookbook/src/app/examples/menu-example/examples/default.ts
  apps/cookbook/src/app/examples/menu-example/examples/portal.ts
  apps/cookbook/src/app/examples/menu-example/examples/portalConfig.ts
  apps/cookbook/src/app/examples/menu-example/examples/selectable.ts
  apps/cookbook/src/app/examples/menu-example/menu-example.component.html
  apps/cookbook/src/app/examples/menu-example/menu-example.module.ts
  apps/cookbook/src/app/showcase/menu-showcase/menu-showcase.component.html
  apps/cookbook/src/app/showcase/menu-showcase/menu-showcase.component.scss
  libs/designsystem/item/src/item.component.scss
  libs/designsystem/menu/src/menu.component.html
  libs/designsystem/menu/src/menu.component.spec.ts
  libs/designsystem/menu/src/menu.component.ts
Labels: feature

#3737 Housekeeping: add angular peer dependencies as dev dependencies
  libs/designsystem/package.json
  libs/extensions/angular/package.json
  package-lock.json
  package.json
Labels: ignore-for-release

#3744 Calendar: fix wrong date when using keyboard nav and UTC timezone
  libs/designsystem/calendar/src/calendar.component.spec.ts
  libs/designsystem/calendar/src/calendar.component.ts
Labels: fix

#3745 Housekeeping: build workspace library deps before running tests
  nx.json
Labels: ignore-for-release
