Repository kirbydesign/designsystem, pull requests merged in 2024-02, with the labels that each got.

#3357 Menu: Fix floating directive performance issues
  libs/designsystem/shared/floating/src/floating.directive.spec.ts
  libs/designsystem/shared/floating/src/floating.directive.ts
Labels: fix

#3367 Range: Fix undefined pinFormatter on initialization
  libs/designsystem/range/src/range.component.spec.ts
  libs/designsystem/range/src/range.component.ts
Labels: fix

#3335 Header: Custom Content in flag section
  apps/cookbook/src/app/examples/header-example/examples/custom-flag.ts
  apps/cookbook/src/app/examples/header-example/header-example.component.html
  apps/cookbook/src/app/examples/header-example/header-example.module.ts
  apps/cookbook/src/app/showcase/header-showcase/header-showcase.component.html
  apps/cookbook/src/app/showcase/header-showcase/header-showcase.component.ts
  libs/designsystem/header/src/header.component.html
  libs/designsystem/header/src/header.component.scss
  libs/designsystem/header/src/header.component.spec.ts
  libs/designsystem/header/src/header.component.ts
  libs/designsystem/header/src/header.module.ts
  libs/designsystem/header/src/public_api.ts
Labels: feature

#3141 Checkbox: Add extra small checkboxes
  apps/cookbook/src/app/examples/checkbox-example/examples/sizes.ts
  apps/cookbook/src/app/examples/checkbox-radio-sizes-example.scss
  apps/cookbook/src/app/showcase/checkbox-showcase/checkbox-showcase.component.html
  libs/core/src/scss/base/_variables.scss
  libs/designsystem/checkbox/src/checkbox.component.scss
  libs/designsystem/checkbox/src/checkbox.component.spec.ts
Labels: enhancement, component:Checkbox, feature

#3380 test: run css transitions immediately
  libs/designsystem/progress-circle/src/progress-circle.component.spec.ts
Labels: ignore-for-release

#3378 Release v9.3.1
  libs/core/package.json
  libs/designsystem/package.json
  package-lock.json
  package.json
Labels: ignore-for-release

#3298 Modal: introduce modal component (declarative modal)
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/modal-example/_modal-playground.shared.scss
  apps/cookbook/src/app/examples/modal-example/modal-component-example.component.scss
  apps/cookbook/src/app/examples/modal-example/modal-component-example.component.ts
  apps/cookbook/src/app/examples/modal-example/modal-example.module.ts
  apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.html
  apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.ts
  libs/core/src/scss/_global-styles.scss
  libs/designsystem/modal/src/modal-wrapper/compact/modal-compact-wrapper.component.html
  libs/designsystem/modal/src/modal-wrapper/compact/modal-compact-wrapper.component.ts
  libs/designsystem/modal/src/modal-wrapper/config/modal-config.ts
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.html
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.scss
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts
  libs/designsystem/modal/src/modal/footer/modal-footer.component.scss
  libs/designsystem/modal/src/modal/index.ts
  libs/designsystem/modal/src/modal/modal-component/modal.component.html
  libs/designsystem/modal/src/modal/modal-component/modal.component.spec.ts
  libs/designsystem/modal/src/modal/modal-component/modal.component.ts
  libs/designsystem/modal/src/modal/services/modal.helper.spec.ts
  libs/designsystem/src/lib/kirby.module.ts
Labels: feature

#3395 Update readme.md to describe how to use Kirby in a standalone apps
  readme.md
Labels: ignore-for-release
