Repository kirbydesign/designsystem, pull requests merged in 2024-03, with the labels that each got.

#3405 Page: Make scrollbar gutter stable to avoid page shifts
  libs/designsystem/page/src/page.component.scss
Labels: feature

#3413 Icons: Add sunshine, revert, fees, crossedeye, common and calendar-start/end
  libs/designsystem/icon/src/icons/svg/calendar-end.svg
  libs/designsystem/icon/src/icons/svg/calendar-start.svg
  libs/designsystem/icon/src/icons/svg/common.svg
  libs/designsystem/icon/src/icons/svg/crossedeye.svg
  libs/designsystem/icon/src/icons/svg/fees.svg
  libs/designsystem/icon/src/icons/svg/revert.svg
  libs/designsystem/icon/src/icons/svg/sunshine.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: feature

#3412 Styles: Update z4 elevation and use in Menu
  libs/core/src/scss/base/_variables.scss
  libs/designsystem/menu/src/menu.component.scss
Labels: fix

#3403 Testing: Add visual regression testing with Chromatic
  .github/workflows/chromatic.yml
  .gitignore
  libs/designsystem/calendar/src/calendar.component.stories.ts
  libs/designsystem/project.json
  package-lock.json
  package.json
Labels: chromatic
