Repository kirbydesign/designsystem, pull requests merged in 2024-11, with the labels that each got.

#3690 Docs: improve calendar showcase
  apps/cookbook/src/app/component-overview/component-configuration.json
  apps/cookbook/src/app/examples/calendar-example/calendar-card-example.component.scss
  apps/cookbook/src/app/examples/calendar-example/calendar-example.component.html
  apps/cookbook/src/app/examples/calendar-example/calendar-example.component.scss
  apps/cookbook/src/app/examples/calendar-example/calendar-example.component.ts
  apps/cookbook/src/app/examples/calendar-example/calendar-example.module.ts
  apps/cookbook/src/app/examples/calendar-example/examples/_shared.scss
  apps/cookbook/src/app/examples/calendar-example/examples/in-card.scss
  apps/cookbook/src/app/examples/calendar-example/examples/in-card.ts
  apps/cookbook/src/app/examples/calendar-example/examples/locales.ts
  apps/cookbook/src/app/examples/calendar-example/examples/no-background.ts
  apps/cookbook/src/app/examples/calendar-example/examples/year-navigator.ts
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/showcase/calendar-showcase/calendar-showcase.component.html
  apps/cookbook/src/app/showcase/calendar-showcase/calendar-showcase.component.scss
  apps/cookbook/src/app/showcase/calendar-showcase/calendar-showcase.component.ts
Labels: ignore-for-release

#3697 Image Banner: Fix dismiss icon intersection on wide variant
  libs/extensions/angular/image-banner/src/image-banner.component.scss
  libs/extensions/angular/image-banner/src/image-banner.component.stories.ts
  libs/extensions/angular/package.json
  package-lock.json
Labels: fix

#3699 Button: add `aria-disabled` support
  apps/cookbook/src/app/examples/button-example/button-example.component.html
  apps/cookbook/src/app/examples/button-example/button-example.module.ts
  apps/cookbook/src/app/examples/button-example/examples/aria-disabled.ts
  apps/cookbook/src/app/showcase/button-showcase/button-showcase.component.html
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/button/src/button.component.spec.ts
  libs/designsystem/button/src/button.component.ts
Labels: feature

#3698 Docs: improve empty state showcase
  apps/cookbook/src/app/component-overview/component-configuration.json
  apps/cookbook/src/app/examples/empty-state-example/empty-state-example.component.html
  apps/cookbook/src/app/examples/empty-state-example/empty-state-example.component.scss
  apps/cookbook/src/app/examples/empty-state-example/empty-state-example.component.ts
  apps/cookbook/src/app/examples/empty-state-example/empty-state-example.module.ts
  apps/cookbook/src/app/examples/empty-state-example/examples/buttons.ts
  apps/cookbook/src/app/examples/empty-state-example/examples/empty-state-example.shared.scss
  apps/cookbook/src/app/examples/empty-state-example/examples/message-types.ts
  apps/cookbook/src/app/examples/empty-state-example/examples/simple.ts
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/showcase/_showcase.shared.scss
  apps/cookbook/src/app/showcase/calendar-showcase/calendar-showcase.component.scss
  apps/cookbook/src/app/showcase/empty-state-showcase/empty-state-showcase.component.html
  apps/cookbook/src/app/showcase/empty-state-showcase/empty-state-showcase.component.scss
  apps/cookbook/src/app/showcase/empty-state-showcase/empty-state-showcase.component.ts
  apps/cookbook/src/app/showcase/header-showcase/header-showcase.component.html
  apps/cookbook/src/app/showcase/header-showcase/header-showcase.component.scss
  apps/cookbook/src/app/showcase/showcase.routes.ts
  libs/designsystem/empty-state/src/empty-state.component.stories.ts
Labels: ignore-for-release

#3689 Calendar: enable keyboard interaction and improve semantics
  apps/cookbook/src/app/showcase/_showcase.shared.scss
  apps/cookbook/src/app/showcase/calendar-showcase/calendar-showcase.component.html
  libs/core/src/scss/interaction-state/_focus.scss
  libs/designsystem/calendar/src/calendar.component.html
  libs/designsystem/calendar/src/calendar.component.scss
  libs/designsystem/calendar/src/calendar.component.spec.ts
  libs/designsystem/calendar/src/calendar.component.ts
  libs/designsystem/calendar/src/helpers/calendar-cell.model.ts
  libs/designsystem/calendar/src/helpers/calendar.helper.ts
  libs/designsystem/calendar/src/interfaces/calendar-day.ts
  libs/designsystem/calendar/src/interfaces/calendar-options.ts
  libs/designsystem/calendar/src/interfaces/calendar-year-navigator-config.ts
  libs/designsystem/calendar/src/public_api.ts
Labels: feature

#3711 Housekeeping: fix failing tests
  libs/designsystem/form-field/src/form-field.component.spec.ts
  libs/designsystem/form-field/src/input/input.component.integration.spec.ts
  libs/designsystem/section-header/src/section-header.component.spec.ts
Labels: housekeeping, ignore-for-release

#3713 Button: add a11y documentation for icon only button
  apps/cookbook/src/app/examples/button-example/examples/disabled.ts
  apps/cookbook/src/app/examples/button-example/examples/icon-only.ts
  apps/cookbook/src/app/examples/button-example/examples/undecorated.ts
  apps/cookbook/src/app/examples/modal-example/modal-route-example/modal-route-page2-example.component.ts
  apps/cookbook/src/app/examples/page-example/advanced/page-advanced-example.component.ts
  apps/cookbook/src/app/examples/page-example/advanced/page-custom-title-example.component.ts
  apps/cookbook/src/app/examples/page-example/fixed-footer-tabs/tab/fixed-footer-tab-example.component.ts
  apps/cookbook/src/app/examples/page-example/fixed-title-and-actions/page-fixed-title-and-actions-example.component.ts
  apps/cookbook/src/app/examples/tabs-example/tab/tab-example.component.ts
  apps/cookbook/src/app/showcase/button-showcase/button-showcase.component.html
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/button/src/button.component.spec.ts
Labels: accessibility, documentation, feature

#3718 Item: improve keyboard interaction and semantics
  apps/cookbook/src/app/showcase/item-showcase/item-showcase.component.ts
  libs/designsystem/item/src/item.component.html
  libs/designsystem/item/src/item.component.integration.spec.ts
  libs/designsystem/item/src/item.component.spec.ts
  libs/designsystem/item/src/item.component.ts
Labels: accessibility, feature

#3723 Icon: margin is missing when slotted to the end inside Item
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/icon/src/icon.component.integration.spec.ts
  libs/designsystem/item/src/item.component.scss
Labels: fix

#3728 Dropdown: fix z-index for overlayed card
  apps/cookbook/src/app/examples/dropdown-example/dropdown-example.module.ts
  apps/cookbook/src/app/examples/examples.common.ts
  libs/core/src/scss/interaction-state/_focus.scss
  libs/designsystem/calendar/src/calendar.component.scss
  libs/designsystem/dropdown/src/dropdown.component.stories.ts
Labels: fix

#3727 Avatar: support lazy loading of image
  apps/cookbook/src/app/examples/avatar-example/avatar-example.component.html
  apps/cookbook/src/app/examples/avatar-example/avatar-example.module.ts
  apps/cookbook/src/app/examples/avatar-example/examples/image-lazy-loading.ts
  apps/cookbook/src/app/showcase/avatar-showcase/avatar-showcase.component.html
  apps/cookbook/src/app/showcase/avatar-showcase/avatar-showcase.component.ts
  libs/designsystem/avatar/src/avatar.component.html
  libs/designsystem/avatar/src/avatar.component.spec.ts
  libs/designsystem/avatar/src/avatar.component.ts
  libs/designsystem/karma.conf.js
  libs/designsystem/testing/images/woman.png
Labels: feature
