Repository kirbydesign/designsystem, pull requests merged in 2024-04, with the labels that each got.

#3431 Modal: ensure footer content doesn't exceed footer width
  libs/designsystem/modal/src/modal/footer/modal-footer.component.scss
  libs/designsystem/modal/src/modal/footer/modal-footer.component.spec.ts
Labels: fix

#3435 Alert: ensure buttons don't overflow the alert
  libs/designsystem/modal/src/modal/alert/alert.component.scss
Labels: fix

#3437 Release v9.4.0
  libs/core/package.json
  libs/designsystem/package.json
  package-lock.json
  package.json
Labels: ignore-for-release

#3423 Calendar: Enable selecting dates in previous and next month
  libs/designsystem/calendar/src/calendar.component.scss
  libs/designsystem/calendar/src/calendar.component.spec.ts
  libs/designsystem/calendar/src/calendar.component.ts
  libs/designsystem/calendar/src/helpers/calendar-cell.model.ts
Labels: feature

#3448 Tab Navigation: Change item padding and gap between items
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.scss
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.scss
Labels: feature

#3447 Docs: Update icon showcase
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/examples/icon-example/examples/custom.ts
  apps/cookbook/src/app/examples/icon-example/examples/default.ts
  apps/cookbook/src/app/examples/icon-example/examples/shared.scss
  apps/cookbook/src/app/examples/icon-example/examples/sizes.ts
  apps/cookbook/src/app/examples/icon-example/icon-example.component.html
  apps/cookbook/src/app/examples/icon-example/icon-example.component.scss
  apps/cookbook/src/app/examples/icon-example/icon-example.component.ts
  apps/cookbook/src/app/examples/icon-example/icon-example.module.ts
  apps/cookbook/src/app/shared/_mini-toast.scss
  apps/cookbook/src/app/showcase/colors-showcase/colors-showcase.component.scss
  apps/cookbook/src/app/showcase/icon-showcase/icon-showcase.component.html
  apps/cookbook/src/app/showcase/icon-showcase/icon-showcase.component.scss
  apps/cookbook/src/app/showcase/icon-showcase/icon-showcase.component.ts
Labels: ignore-for-release

#3449 Tab Navigation: Make item label text truncation optional
  apps/cookbook/src/app/examples/page-example/tab-navigation/page-tab-nav-example.component.ts
  apps/cookbook/src/app/showcase/page-showcase/page-showcase.component.html
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.html
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.scss
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.spec.ts
  libs/designsystem/tab-navigation/src/tab-navigation-item/tab-navigation-item.component.ts
Labels: feature

#3452 Calendar: fix selecting dates in previous and next month
  libs/designsystem/calendar/src/calendar.component.spec.ts
  libs/designsystem/calendar/src/calendar.component.ts
Labels: fix

#3456 Tab Navigation: Remove unwanted right margin on content
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.scss
Labels: feature

#3460 Section Header: Fix layering (visible through tab navigation)
  libs/designsystem/section-header/src/section-header.component.scss
  libs/designsystem/section-header/src/section-header.component.spec.ts
Labels: fix

#3462 Segmented control looses its checked state when items are updated
  apps/cookbook/src/app/examples/segmented-control-example/color/color.ts
  apps/cookbook/src/app/examples/segmented-control-example/default/default.ts
  apps/cookbook/src/app/examples/segmented-control-example/with-badge/with-badge.ts
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts
Labels: fix
