Repository kirbydesign/designsystem, pull requests merged in 2024-09, with the labels that each got.

#3542 Docs: Add missing kirby-divider in cookbook accordion example
  apps/cookbook/src/app/examples/accordion-example/examples/list-items.ts
Labels: cookbook, ignore-for-release

#3573 Icon: remove deprecated `customName` property
  apps/cookbook/src/app/examples/icon-example/examples/custom.ts
  apps/cookbook/src/app/showcase/empty-state-showcase/empty-state-showcase.component.ts
  apps/cookbook/src/app/showcase/icon-showcase/icon-showcase.component.html
  apps/cookbook/src/app/showcase/icon-showcase/icon-showcase.component.ts
  libs/designsystem/empty-state/src/empty-state.component.html
  libs/designsystem/empty-state/src/empty-state.component.stories.ts
  libs/designsystem/empty-state/src/empty-state.component.ts
  libs/designsystem/icon/src/icon.component.spec.ts
  libs/designsystem/icon/src/icon.component.stories.ts
  libs/designsystem/icon/src/icon.component.ts
  libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.html
  libs/designsystem/testing-base/src/lib/components/mock.empty-state.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.icon.component.ts
Labels: breaking-change

#3572 Page: remove deprecated `MaxWidth` options
  libs/core/src/scss/base/_variables.scss
  libs/designsystem/page/src/page.component.scss
  libs/designsystem/page/src/page.component.spec.ts
  libs/designsystem/page/src/page.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.page.component.ts
Labels: breaking-change

#3574 Page Local Navigation: remove (deprecated)
  apps/cookbook/src/app/app.module.ts
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/experimental-examples/components/index.ts
  apps/cookbook/src/app/examples/experimental-examples/components/page-local-navigation/page-local-navigation-example.component.ts
  apps/cookbook/src/app/examples/experimental-examples/experimental-examples.module.ts
  libs/designsystem/src/lib/components/index.ts
  libs/designsystem/src/lib/components/page-local-navigation/index.ts
  libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation-item.ts
  libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.html
  libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.scss
  libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.spec.ts
  libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby-experimental.module.ts
  libs/designsystem/testing-base/src/lib/components/index.ts
  libs/designsystem/testing-base/src/lib/components/mock.page-local-navigation.component.ts
  libs/designsystem/testing-base/src/lib/mock-components.ts
Labels: breaking-change

#3575 Tabs: remove deprecated `routerLink` input
  apps/cookbook/src/app/examples/page-example/fixed-footer-tabs/fixed-footer-tabs-example.component.ts
  apps/cookbook/src/app/examples/tabs-example/tabs-example.component.html
  apps/cookbook/src/app/showcase/tabs-showcase/tabs-showcase.component.html
  apps/cookbook/src/app/showcase/tabs-showcase/tabs-showcase.component.ts
  apps/flows/src/app/transaction-details-flow/transaction-details-flow.component.html
  libs/designsystem/tabs/src/tab-button/tab-button.component.html
  libs/designsystem/tabs/src/tab-button/tab-button.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.tab-button.component.ts
Labels: breaking-change

#3588 Modal: remove deprecated alert config
  libs/designsystem/modal/src/modal-navigation.service.ts
  libs/designsystem/modal/src/modal.interfaces.ts
  libs/designsystem/modal/src/modal/services/modal.controller.ts
  libs/designsystem/modal/src/modal/services/modal.helper.ts
  libs/designsystem/src/lib/directives/modal-router-link/modal-router-link.directive.ts
Labels: breaking-change

#3576 Data Table: remove deprecated `Table` component
  apps/cookbook/src/app/examples/data-table-example/examples/card.ts
  apps/cookbook/src/app/examples/data-table-example/examples/default.ts
  apps/cookbook/src/app/examples/data-table-example/examples/sortable.ts
  apps/cookbook/src/app/examples/data-table-example/table-example.module.ts
  apps/cookbook/src/app/showcase/data-table-showcase/data-table-showcase.component.html
  libs/designsystem/data-table/src/data-table.module.ts
  libs/designsystem/data-table/src/public_api.ts
  libs/designsystem/data-table/src/sortable/sortable.component.spec.ts
  libs/designsystem/data-table/src/sortable/sortable.component.ts
  libs/designsystem/data-table/src/table-row/table-row.component.spec.ts
  libs/designsystem/data-table/src/table-row/table-row.component.ts
  libs/designsystem/data-table/src/table/table.component.scss
  libs/designsystem/data-table/src/table/table.component.spec.ts
  libs/designsystem/data-table/src/table/table.component.stories.ts
  libs/designsystem/data-table/src/table/table.component.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/testing-base/src/lib/components/index.ts
  libs/designsystem/testing-base/src/lib/components/mock.table-row.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.table.component.ts
  libs/designsystem/testing-base/src/lib/mock-components.ts
Labels: breaking-change

#3592 Card: remove deprecated flat property
  apps/cookbook/src/app/showcase/badge-showcase/badge-showcase.component.html
  apps/cookbook/src/app/showcase/chart-showcase/chart-showcase.component.html
  apps/cookbook/src/app/showcase/item-sliding-showcase/item-sliding-showcase.component.html
  apps/cookbook/src/app/showcase/stock-chart-showcase/stock-chart-showcase.component.html
  libs/designsystem/card/src/card.component.ts
Labels: breaking-change

#3598 Modal: Remove experimental modal v2
  apps/cookbook/src/app/app.module.ts
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/modal-example/modal-example.module.ts
  apps/cookbook/src/app/examples/modal-v2-example/controller/modal-controller-v2-example.component.html
  apps/cookbook/src/app/examples/modal-v2-example/controller/modal-controller-v2-example.component.ts
  apps/cookbook/src/app/examples/modal-v2-example/modal-routing/modal-routing-v2-example-page1.component.ts
  apps/cookbook/src/app/examples/modal-v2-example/modal-routing/modal-routing-v2-example-page2.component.ts
  apps/cookbook/src/app/examples/modal-v2-example/modal-routing/modal-routing-v2-example.component.html
  apps/cookbook/src/app/examples/modal-v2-example/modal-routing/modal-routing-v2-example.component.ts
  apps/cookbook/src/app/examples/modal-v2-example/modal-v2-example.module.ts
  apps/cookbook/src/app/examples/modal-v2-example/modal/drawer/drawer-v2-example.component.html
  apps/cookbook/src/app/examples/modal-v2-example/modal/drawer/drawer-v2-example.component.scss
  apps/cookbook/src/app/examples/modal-v2-example/modal/drawer/drawer-v2-example.component.ts
  apps/cookbook/src/app/examples/modal-v2-example/modal/fullscreen/fullscreen-v2-example.component.html
  apps/cookbook/src/app/examples/modal-v2-example/modal/fullscreen/fullscreen-v2-example.component.scss
  apps/cookbook/src/app/examples/modal-v2-example/modal/fullscreen/fullscreen-v2-example.component.ts
  apps/cookbook/src/app/examples/modal-v2-example/nested-modals/nested-modals-v2-example.component.html
  apps/cookbook/src/app/examples/modal-v2-example/nested-modals/nested-modals-v2-example.component.scss
  apps/cookbook/src/app/examples/modal-v2-example/nested-modals/nested-modals-v2-example.component.ts
  apps/cookbook/src/app/showcase/modal-v2-showcase/modal-v2-showcase.component.html
  apps/cookbook/src/app/showcase/modal-v2-showcase/modal-v2-showcase.component.scss
  apps/cookbook/src/app/showcase/modal-v2-showcase/modal-v2-showcase.component.ts
  apps/cookbook/src/app/showcase/showcase.common.ts
  apps/cookbook/src/app/showcase/showcase.module.ts
  apps/cookbook/src/app/showcase/showcase.routes.ts
  libs/core/src/scss/_global-styles.scss
  libs/core/src/scss/base/_variables.scss
  libs/designsystem/modal/v2/index.ts
  libs/designsystem/modal/v2/ng-package.json
  libs/designsystem/modal/v2/src/footer/footer.component.html
  libs/designsystem/modal/v2/src/footer/footer.component.scss
  libs/designsystem/modal/v2/src/footer/footer.component.spec.ts
  libs/designsystem/modal/v2/src/footer/footer.component.ts
  libs/designsystem/modal/v2/src/index.ts
  libs/designsystem/modal/v2/src/kirby-modal.module.ts
  libs/designsystem/modal/v2/src/modal-routing/modal-routing.component.html
  libs/designsystem/modal/v2/src/modal-routing/modal-routing.component.scss
  libs/designsystem/modal/v2/src/modal-routing/modal-routing.component.ts
  libs/designsystem/modal/v2/src/modal/modal.component.html
  libs/designsystem/modal/v2/src/modal/modal.component.scss
  libs/designsystem/modal/v2/src/modal/modal.component.ts
  libs/designsystem/modal/v2/src/public_api.ts
  libs/designsystem/modal/v2/src/services/modal.controller.ts
  libs/designsystem/modal/v2/src/wrapper/wrapper.component.html
  libs/designsystem/modal/v2/src/wrapper/wrapper.component.scss
  libs/designsystem/modal/v2/src/wrapper/wrapper.component.spec.ts
  libs/designsystem/modal/v2/src/wrapper/wrapper.component.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/testing-base/src/lib/components/index.ts
  libs/designsystem/testing-base/src/lib/components/mock.footer.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.modal-routing.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.modal.component.ts
  libs/designsystem/testing-base/src/lib/components/mock.wrapper.component.ts
  libs/designsystem/testing-base/src/lib/mock-components.ts
  libs/designsystem/tsconfig.spec.json
  tsconfig.base.json
Labels: breaking-change

#3594 Testing: Add chromatic viewport modes
  libs/designsystem/.storybook/preview.ts
  libs/designsystem/calendar/src/calendar.component.stories.ts
  libs/designsystem/header/src/header.component.stories.ts
  libs/designsystem/page/src/page.component.stories.ts
  libs/designsystem/slide/src/slides.component.stories.ts
  libs/extensions/angular/.storybook/preview.ts
  libs/extensions/angular/image-banner/src/image-banner.component.stories.ts
  tools/storybook-config/shared-config.ts
Labels: ignore-for-release

#3596 Image Banner: fix content not shown in large viewport
  libs/extensions/angular/image-banner/src/image-banner.component.scss
Labels: ignore-for-release

#3604 Housekeeping: Bump jest-preset-angular
  libs/extensions/angular/package.json
  package-lock.json
Labels: ignore-for-release

#3600 Docs: add DataTable to Storybook
  apps/cookbook/src/app/examples/data-table-example/data-table-example.component.html
  apps/cookbook/src/app/examples/data-table-example/data-table-example.component.ts
  apps/cookbook/src/app/examples/data-table-example/table-example.module.ts
  apps/cookbook/src/app/examples/examples.common.ts
  libs/designsystem/data-table/src/data-table.stories.ts
Labels: documentation, ignore-for-release

#3602 Test: add logging to flaky tests
  libs/designsystem/dropdown/src/dropdown.component.spec.ts
  libs/designsystem/page/src/page.component.spec.ts
Labels: ignore-for-release

#3609 Housekeeping: Create Cookbook example story for Card
  apps/cookbook/src/app/examples/card-example/card-example.module.ts
  libs/designsystem/card/src/card.component.stories.ts
Labels: ignore-for-release

#3601 Icon: Customizable icon asset path
  apps/cookbook/src/app/showcase/icon-showcase/icon-showcase.component.html
  apps/cookbook/src/app/showcase/icon-showcase/icon-showcase.component.ts
  libs/designsystem/icon/src/icon-registry.service.spec.ts
  libs/designsystem/icon/src/icon-registry.service.ts
  libs/designsystem/icon/src/kirby-icon-settings.ts
  readme.md
Labels: feature

#3621 Housekeeping: prepare release of extensions-angular
  libs/extensions/angular/README.md
  libs/extensions/angular/package.json
Labels: ignore-for-release

#3625 Housekeeping: Create Cookbook example story for Accordion
  apps/cookbook/src/app/examples/accordion-example/accordion-example.component.scss
  apps/cookbook/src/app/examples/accordion-example/accordion-example.component.ts
  apps/cookbook/src/app/examples/accordion-example/accordion-example.module.ts
  apps/cookbook/src/app/examples/examples.common.ts
  libs/designsystem/accordion/src/accordion-item.component.stories.ts
Labels: ignore-for-release

#3623 Alert: use primary color instead of success color for ok button
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/modal/src/modal/alert/alert.component.spec.ts
Labels: fix

#3631 Textarea: missing resize handle
  libs/designsystem/form-field/src/textarea/textarea.component.scss
  libs/designsystem/form-field/src/textarea/textarea.component.spec.ts
Labels: bug, ignore-for-release

#3633 Toggle Button: respect disabled state of slotted buttons
  apps/cookbook/src/app/examples/toggle-button-example/toggle-button-example.component.ts
  libs/designsystem/toggle-button/src/toggle-button.component.html
  libs/designsystem/toggle-button/src/toggle-button.component.spec.ts
  libs/designsystem/toggle-button/src/toggle-button.component.ts
Labels: fix

#3635 Housekeeping: Use storybooks staticDir for assets in extensions lib
  libs/extensions/angular/.storybook/main.ts
  libs/extensions/angular/image-banner/src/image-banner.component.stories.ts
  libs/extensions/angular/project.json
Labels: ignore-for-release

#3634 Update package-lock.json
  package-lock.json
Labels: ignore-for-release

#3639 Housekeeping: Refactor `Button` docs
  apps/cookbook/src/app/examples/button-example/button-example.component.html
  apps/cookbook/src/app/examples/button-example/button-example.component.scss
  apps/cookbook/src/app/examples/button-example/button-example.component.ts
  apps/cookbook/src/app/examples/button-example/button-example.module.ts
  apps/cookbook/src/app/examples/button-example/examples/_grid-layout.scss
  apps/cookbook/src/app/examples/button-example/examples/_responsive-grid-layout.scss
  apps/cookbook/src/app/examples/button-example/examples/_shared.scss
  apps/cookbook/src/app/examples/button-example/examples/attention-level.scss
  apps/cookbook/src/app/examples/button-example/examples/attention-level.ts
  apps/cookbook/src/app/examples/button-example/examples/block.ts
  apps/cookbook/src/app/examples/button-example/examples/default.ts
  apps/cookbook/src/app/examples/button-example/examples/disabled.ts
  apps/cookbook/src/app/examples/button-example/examples/icon-only.ts
  apps/cookbook/src/app/examples/button-example/examples/icons.ts
  apps/cookbook/src/app/examples/button-example/examples/link.ts
  apps/cookbook/src/app/examples/button-example/examples/sizes.scss
  apps/cookbook/src/app/examples/button-example/examples/sizes.ts
  apps/cookbook/src/app/examples/button-example/examples/undecorated.ts
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/shared/example-viewer/example-viewer.component.scss
  apps/cookbook/src/app/showcase/button-showcase/button-showcase.component.html
  apps/cookbook/src/app/showcase/button-showcase/button-showcase.component.scss
  apps/cookbook/src/app/showcase/button-showcase/button-showcase.component.ts
  libs/designsystem/button/src/button.component.stories.ts
Labels: housekeeping, documentation, ignore-for-release

#3628 Enhancement: Add keyboard support to slide button
  libs/core/src/scss/interaction-state/_focus.scss
  libs/designsystem/slide-button/src/slide-button.component.html
  libs/designsystem/slide-button/src/slide-button.component.scss
  libs/designsystem/slide-button/src/slide-button.component.ts
Labels: feature
