Repository kirbydesign/designsystem, pull requests merged in 2024-10, with the labels that each got.

#3649 Checkbox, Radio: fix slotted text not wrapping
  libs/designsystem/checkbox/src/checkbox.component.scss
  libs/designsystem/radio/src/radio.component.scss
Labels: fix

#3647 Item: fix wrong text alignment of slotted controls with multiline labels
  libs/designsystem/form-field/src/form-field.component.spec.ts
  libs/designsystem/form-field/src/input/input.component.integration.spec.ts
  libs/designsystem/item/src/item.component.scss
  libs/designsystem/item/src/item.component.stories.ts
Labels: fix

#3644 Icons: Sort by name
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: ignore-for-release

#3654 Docs: fix side menu state
  apps/cookbook/src/app/page/side-nav/side-nav.component.ts
Labels: housekeeping, documentation, ignore-for-release

#3552 Accordion: Support for lists within accordions
  apps/cookbook/src/app/examples/accordion-example/accordion-example.component.html
  apps/cookbook/src/app/examples/accordion-example/accordion-example.module.ts
  apps/cookbook/src/app/examples/accordion-example/examples/card-list.ts
  apps/cookbook/src/app/examples/accordion-example/examples/list-items.ts
  apps/cookbook/src/app/examples/accordion-example/examples/list.ts
  apps/cookbook/src/app/showcase/accordion-showcase/accordion-showcase.component.html
  apps/cookbook/src/app/showcase/accordion-showcase/accordion-showcase.component.scss
  libs/designsystem/accordion/src/accordion-item.component.scss
  libs/designsystem/accordion/src/accordion-item.component.spec.ts
  libs/designsystem/accordion/src/accordion-item.component.ts
Labels: feature

#3661 Icon: Add drag-drop
  libs/designsystem/icon/src/icons/svg/drag-drop.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: feature

#3657 Checkbox, Radio: infer label text when used with label and item
  apps/cookbook/src/app/showcase/checkbox-showcase/checkbox-showcase.component.html
  apps/cookbook/src/app/showcase/radio-showcase/radio-showcase.component.html
  libs/designsystem/checkbox/src/checkbox.component.html
  libs/designsystem/checkbox/src/checkbox.component.scss
  libs/designsystem/checkbox/src/checkbox.component.ts
  libs/designsystem/item/src/item.component.stories.ts
  libs/designsystem/item/src/item.component.ts
  libs/designsystem/project.json
  libs/designsystem/radio/src/radio.component.html
  libs/designsystem/radio/src/radio.component.scss
  libs/designsystem/radio/src/radio.component.ts
  libs/designsystem/shared/src/controls/label-helpers.ts
  libs/designsystem/shared/src/public_api.ts
Labels: feature

#3662 Release v10.1.0
  libs/core/package.json
  libs/designsystem/package.json
  package-lock.json
Labels: ignore-for-release

#3659 Housekeeping: Create Cookbook example story for Icon
  apps/cookbook/src/app/examples/examples.common.ts
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/examples/icon-example/icon-example.module.ts
  libs/designsystem/icon/src/icon.component.stories.ts
Labels: ignore-for-release

#3664 Image Banner: use container queries to support usage in kirby-grid and kirby-slides
  libs/extensions/angular/image-banner/src/image-banner.component.scss
  libs/extensions/angular/image-banner/src/image-banner.component.stories.ts
  libs/extensions/angular/package.json
  package-lock.json
Labels: feature

#3668 Core: declare interaction-state, variables and colors scss exports
  libs/core/package.json
  libs/designsystem/package.json
  package-lock.json
Labels: fix

#3669 Core: declare print scss export
  libs/core/package.json
  libs/designsystem/package.json
  package-lock.json
Labels: fix

#3672 Housekeeping: update eslint dependency and add base config
  apps/cookbook/src/app/examples/alert-example/alert-example.component.ts
  apps/cookbook/src/app/examples/modal-example/modal-example-advanced.component.ts
  apps/cookbook/src/app/examples/modal-example/modal-example-alert-with-guard.component.ts
  apps/cookbook/src/app/examples/page-example/advanced/page-advanced-example.component.ts
  apps/cookbook/src/app/examples/page-example/advanced/page-custom-title-example.component.ts
  apps/cookbook/src/app/examples/page-example/fixed-title-and-actions/page-fixed-title-and-actions-example.component.ts
  apps/cookbook/src/app/iphone/iphone.component.ts
  apps/cookbook/src/app/showcase/showcase.component.ts
  apps/flows/src/app/transfer-and-pay-flow/choose-date/choose-date.component.ts
  apps/flows/src/app/transfer-and-pay-flow/choose-text-and-message/choose-text-and-message.component.ts
  apps/flows/src/app/transfer-and-pay-flow/other-page/other-page.component.ts
  libs/core/.eslintrc.json
  libs/core/src/badge/badge.element.styles.ts
  libs/designsystem/button/src/button.component.ts
  libs/designsystem/calendar/src/calendar.component.ts
  libs/designsystem/card/src/card-as-button/card-as-button.directive.ts
  libs/designsystem/flag/src/flag.component.spec.ts
  libs/designsystem/form-field/src/directives/decimal-mask/decimal-mask.directive.ts
  libs/designsystem/icon/src/icon-registry.service.ts
  libs/designsystem/list/src/directives/infinite-scroll.directive.ts
  libs/designsystem/modal/src/modal-navigation.service.ts
  libs/designsystem/modal/src/modal-wrapper/modal-elements-mover.delegate.ts
  libs/designsystem/modal/src/modal/alert/alert.component.ts
  libs/designsystem/popover/src/popover.component.ts
  libs/designsystem/slide/src/slide-stretch-height.directive.ts
  libs/designsystem/slide/src/slides.component.ts
  libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.ts
  libs/designsystem/toggle/src/toggle.component.ts
  package-lock.json
  package.json
  tools/eslint-config/angular.json
  tools/eslint-config/base.json
  tools/eslint-config/eslintrc-custom-overrides.json
  tools/eslint-config/package.json
Labels: ignore-for-release

#3676 Icon: remove title and desc element
  libs/designsystem/icon/src/icons/svg/accounts-outline.svg
  libs/designsystem/icon/src/icons/svg/accounts.svg
  libs/designsystem/icon/src/icons/svg/backspace.svg
  libs/designsystem/icon/src/icons/svg/camera.svg
  libs/designsystem/icon/src/icons/svg/copy.svg
  libs/designsystem/icon/src/icons/svg/flag.svg
  libs/designsystem/icon/src/icons/svg/inbox-outline.svg
  libs/designsystem/icon/src/icons/svg/inbox.svg
  libs/designsystem/icon/src/icons/svg/information.svg
  libs/designsystem/icon/src/icons/svg/menu-outline.svg
  libs/designsystem/icon/src/icons/svg/menu.svg
  libs/designsystem/icon/src/icons/svg/person-outline.svg
  libs/designsystem/icon/src/icons/svg/person.svg
  libs/designsystem/icon/src/icons/svg/reorder.svg
  libs/designsystem/icon/src/icons/svg/support.svg
Labels: fix

#3674 Docs: improve button icon only example
  apps/cookbook/src/app/examples/button-example/examples/icon-only.ts
Labels: cookbook, documentation, ignore-for-release

#3685 Docs: Add page and nav menu item for extensions
  apps/cookbook/src/app/app.routes.ts
  apps/cookbook/src/app/extensions/extensions-landing-page.component.html
  apps/cookbook/src/app/extensions/extensions-landing-page.component.ts
  apps/cookbook/src/app/page/header/header.component.ts
  libs/extensions/angular/README.md
Labels: ignore-for-release
