Repository kirbydesign/designsystem, pull requests merged in 2024-08, with the labels that each got.

#3519 Housekeeping: Remove unexpected file extension (.scss)
  apps/cookbook/src/app/examples/avatar-example/examples/badge.scss
  apps/cookbook/src/app/examples/card-example/examples/card-example-variant.scss
  apps/cookbook/src/app/examples/segmented-control-example/color/color.scss
  libs/designsystem/item-sliding/src/item-sliding.component.scss
Labels: ignore-for-release

#3518 Page: fix dynamic title
  libs/designsystem/header/src/header.component.ts
  libs/designsystem/page/src/page.component.ts
Labels: fix

#3513 Avatar: emit error event when loading img fails
  apps/cookbook/src/app/examples/avatar-example/avatar-example.module.ts
  apps/cookbook/src/app/examples/avatar-example/examples/image-error.ts
  apps/cookbook/src/app/showcase/avatar-showcase/avatar-showcase.component.html
  apps/cookbook/src/app/showcase/avatar-showcase/avatar-showcase.component.ts
  apps/cookbook/src/assets/images/avatar-not-found.png
  libs/designsystem/avatar/src/avatar.component.html
  libs/designsystem/avatar/src/avatar.component.spec.ts
  libs/designsystem/avatar/src/avatar.component.ts
Labels: feature

#3535 Button: allow adding kirby-button directive to anchor tags
  apps/cookbook/src/app/examples/button-example/button-example.component.html
  libs/designsystem/button/src/button.component.scss
  libs/designsystem/button/src/button.component.ts
Labels: feature

#3536 Docs: Replace custom dots in item flag examples with small badge
  apps/cookbook/src/app/examples/item-example/examples/avatar/flagged-three-lines.ts
  apps/cookbook/src/app/examples/item-example/examples/avatar/flagged.ts
  apps/cookbook/src/app/examples/item-example/examples/flagged.ts
  apps/cookbook/src/app/showcase/item-showcase/item-showcase.component.html
Labels: ignore-for-release

#3538 Cookbook: Fix missing logo link text
  apps/cookbook/src/app/page/header/header.component.html
Labels: ignore-for-release

#3540 Docs: remove page progress from drawer examples
  apps/cookbook/src/app/examples/modal-example/embedded-modal-example/embedded-modal-example.component.html
  apps/cookbook/src/app/examples/modal-example/embedded-modal-example/embedded-modal-example.component.ts
  apps/cookbook/src/app/examples/modal-example/modal-example-advanced.component.ts
  apps/cookbook/src/app/examples/modal-example/modal-example-configuration/modal-example-configuration.component.html
  apps/cookbook/src/app/examples/modal-example/modal-example-configuration/modal-example-configuration.component.ts
Labels: ignore-for-release

#3546 Housekeeping: Add stories for radio
  apps/cookbook/src/app/examples/checkbox-example/checkbox-example.module.ts
  apps/cookbook/src/app/examples/example-configuration-wrapper/example-configuration-wrapper.component.ts
  apps/cookbook/src/app/examples/examples.module.ts
  apps/cookbook/src/app/examples/examples.shared.module.ts
  apps/cookbook/src/app/examples/experimental-examples/experimental-examples.module.ts
  apps/cookbook/src/app/examples/modal-example/modal-example.module.ts
  apps/cookbook/src/app/examples/modal-v2-example/modal-v2-example.module.ts
  apps/cookbook/src/app/examples/radio-example/radio-example.module.ts
  apps/cookbook/src/app/examples/reactive-form-state/reactive-form.module.ts
  apps/cookbook/src/app/examples/toggle-example/toggle-example.module.ts
  libs/designsystem/item/src/item.component.stories.ts
  libs/designsystem/radio/src/radio-group/radio-group.component.stories.ts
Labels: ignore-for-release

#3550 General: output design tokens as CSS custom properties
  .gitignore
  libs/core/src/scss/_global-styles.scss
  libs/core/src/scss/_utils.scss
  libs/core/src/scss/base/_design-tokens.scss
  libs/core/src/scss/themes/_colors.scss
  libs/core/src/scss/themes/_component-themes.scss
  libs/core/src/scss/themes/design-tokens.scss
  package.json
Labels: feature

#3558 Test: fix failing tests related to screensize
  libs/designsystem/header/src/header.component.spec.ts
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.spec.ts
  libs/designsystem/modal/src/modal/footer/modal-footer.component.spec.ts
  libs/designsystem/modal/src/modal/services/modal.helper.spec.ts
  libs/designsystem/modal/v2/src/footer/footer.component.spec.ts
Labels: housekeeping, ignore-for-release

#3557 docs: add radio stories before Ionic upgrade
  apps/cookbook/src/app/examples/radio-example/radio-example.component.html
  libs/designsystem/item/src/item.component.stories.ts
Labels: documentation, ignore-for-release

#3559 docs: add checkbox stories before Ionic upgrade
  apps/cookbook/src/app/examples/checkbox-example/checkbox-example.component.html
  apps/cookbook/src/app/examples/checkbox-example/checkbox-example.module.ts
  apps/cookbook/src/app/examples/examples.common.ts
  libs/designsystem/checkbox/src/checkbox.component.stories.ts
  libs/designsystem/item/src/item.component.stories.ts
Labels: housekeeping, documentation, ignore-for-release

#3561 docs: add item with complex label
  libs/designsystem/item/src/item.component.stories.ts
Labels: housekeeping, documentation, ignore-for-release
