Repository kirbydesign/designsystem, pull requests merged in 2025-04, with the labels that each got.

#3814 Radio Group: support aria-label and aria-labelledby
  apps/cookbook/src/app/examples/radio-example/examples/binding.ts
  apps/cookbook/src/app/examples/radio-example/examples/custom.ts
  apps/cookbook/src/app/examples/radio-example/examples/default.ts
  apps/cookbook/src/app/examples/radio-example/examples/in-item.ts
  apps/cookbook/src/app/examples/radio-example/examples/sizes.ts
  apps/cookbook/src/app/examples/radio-example/examples/states.ts
  apps/cookbook/src/app/showcase/radio-showcase/radio-showcase.component.html
  libs/designsystem/radio/src/radio-group/radio-group.component.spec.ts
  libs/designsystem/radio/src/radio-group/radio-group.component.ts
  libs/designsystem/shared/src/controls/label-helpers.spec.ts
  libs/designsystem/shared/src/controls/label-helpers.ts
Labels: feature

#3845 Docs: improve toast showcase
  apps/cookbook/src/app/examples/_modal-playground.shared.scss
  apps/cookbook/src/app/examples/examples.routes.ts
  apps/cookbook/src/app/examples/modal-example/modal-component-example.component.scss
  apps/cookbook/src/app/examples/modal-example/modal-example-advanced.component.scss
  apps/cookbook/src/app/examples/modal-example/modal-example-outlet.component.scss
  apps/cookbook/src/app/examples/modal-example/modal-example-simple.component.scss
  apps/cookbook/src/app/examples/toast-example/toast-example.component.html
  apps/cookbook/src/app/examples/toast-example/toast-example.component.ts
  apps/cookbook/src/app/showcase/modal-showcase/modal-showcase.component.html
  apps/cookbook/src/app/showcase/toast-showcase/toast-showcase.component.html
  apps/cookbook/src/app/showcase/toast-showcase/toast-showcase.component.scss
  apps/cookbook/src/app/showcase/toast-showcase/toast-showcase.component.ts
Labels: ignore-for-release

#3870 Global Config + Page: add support for focus of h1 and setting html doc title on page enter
  apps/cookbook/src/app/examples/page-example/base-page-example.component.ts
  apps/cookbook/src/main.ts
  libs/designsystem/.storybook/preview.ts
  libs/designsystem/config/index.ts
  libs/designsystem/config/ng-package.json
  libs/designsystem/config/src/index.ts
  libs/designsystem/config/src/provide-kirby.ts
  libs/designsystem/config/src/public_api.ts
  libs/designsystem/header/src/header.component.html
  libs/designsystem/header/src/header.component.scss
  libs/designsystem/header/src/header.component.spec.ts
  libs/designsystem/kirby-ionic-module/src/kirby-ionic.module.ts
  libs/designsystem/kirby-ionic-module/src/public_api.ts
  libs/designsystem/modal/src/modal/modal-component/modal.component.ts
  libs/designsystem/page/src/page.component.html
  libs/designsystem/page/src/page.component.scss
  libs/designsystem/page/src/page.component.spec.ts
  libs/designsystem/page/src/page.component.ts
  libs/designsystem/router-outlet/src/router-outlet.integration.spec.ts
  libs/designsystem/shared/src/fit-heading/fit-heading.directive.ts
  libs/designsystem/src/lib/index.ts
  libs/designsystem/src/lib/kirby.module.ts
  libs/designsystem/tsconfig.spec.json
  libs/extensions/angular/.storybook/preview.ts
  readme.md
  tsconfig.base.json
Labels: feature

#3872 Toggle Button: Implement ControlValueAccessor to support Angular forms
  apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts
  apps/cookbook/src/app/examples/toggle-button-example/examples/reactive-forms.ts
  apps/cookbook/src/app/examples/toggle-button-example/toggle-button-example.component.html
  apps/cookbook/src/app/examples/toggle-button-example/toggle-button-example.component.ts
  apps/cookbook/src/app/showcase/checkbox-showcase/checkbox-showcase.component.html
  apps/cookbook/src/app/showcase/radio-showcase/radio-showcase.component.html
  apps/cookbook/src/app/showcase/toggle-button-showcase/toggle-button-showcase.component.html
  apps/cookbook/src/app/showcase/toggle-button-showcase/toggle-button-showcase.component.ts
  apps/cookbook/src/app/showcase/toggle-showcase/toggle-showcase.component.html
  libs/designsystem/toggle-button/src/toggle-button.component.spec.ts
  libs/designsystem/toggle-button/src/toggle-button.component.ts
Labels: feature

#3873 Segmented Control: Implement ControlValueAccessor to support Angular forms
  apps/cookbook/src/app/examples/segmented-control-example/reactive-forms/reactive-forms.ts
  apps/cookbook/src/app/examples/segmented-control-example/segmented-control-example.component.html
  apps/cookbook/src/app/examples/segmented-control-example/segmented-control-example.component.ts
  apps/cookbook/src/app/examples/toggle-button-example/examples/reactive-forms.ts
  apps/cookbook/src/app/showcase/segmented-control-showcase/segmented-control-showcase.component.html
  apps/cookbook/src/app/showcase/segmented-control-showcase/segmented-control-showcase.component.ts
  apps/cookbook/src/app/showcase/toggle-button-showcase/toggle-button-showcase.component.html
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.html
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.spec.ts
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts
Labels: feature

#3882 Checkbox: Add indeterminate state
  apps/cookbook/src/app/examples/checkbox-example/checkbox-example.component.html
  apps/cookbook/src/app/examples/checkbox-example/checkbox-example.component.ts
  apps/cookbook/src/app/examples/checkbox-example/examples/list-indeterminate.ts
  apps/cookbook/src/app/examples/checkbox-example/examples/states.ts
  apps/cookbook/src/app/showcase/checkbox-showcase/checkbox-showcase.component.html
  apps/cookbook/src/app/showcase/checkbox-showcase/checkbox-showcase.component.ts
  libs/designsystem/checkbox/src/checkbox.component.html
  libs/designsystem/checkbox/src/checkbox.component.scss
  libs/designsystem/checkbox/src/checkbox.component.spec.ts
  libs/designsystem/checkbox/src/checkbox.component.stories.ts
  libs/designsystem/checkbox/src/checkbox.component.ts
Labels: feature

#3891 Release v10.4.0
  libs/core/package.json
  libs/designsystem/package.json
  package-lock.json
Labels: ignore-for-release

#3893 Page: fix unnecessary ellipsis on title
  libs/core/package.json
  libs/core/src/scss/base/_line-clamp.scss
  libs/designsystem/package.json
  libs/designsystem/shared/src/fit-heading/fit-heading.directive.ts
Labels: fix

#3898 Checkbox, Radio, Toggle: fix screen reader announcement of both visible and aria label
  libs/designsystem/checkbox/src/checkbox.component.html
  libs/designsystem/radio/src/radio.component.html
  libs/designsystem/toggle/src/toggle.component.html
Labels: fix

#3897 Checkbox, Radio, Toggle: fix click area expanding outside of element when not in item
  libs/designsystem/checkbox/src/checkbox.component.scss
  libs/designsystem/checkbox/src/checkbox.component.spec.ts
  libs/designsystem/radio/src/radio.component.scss
  libs/designsystem/radio/src/radio.component.spec.ts
  libs/designsystem/toggle/src/toggle.component.scss
  libs/designsystem/toggle/src/toggle.component.spec.ts
Labels: fix

#3874 Input & Textarea: emit kirbyChange on form value change
  apps/cookbook/src/app/examples/form-field-example/examples/input/reactive-forms.ts
  apps/cookbook/src/app/examples/form-field-example/examples/textarea/reactive-forms.ts
  apps/cookbook/src/app/examples/form-field-example/form-field-example.component.html
  apps/cookbook/src/app/examples/form-field-example/form-field-example.component.ts
  apps/cookbook/src/app/showcase/form-field-showcase/form-field-showcase.component.html
  apps/cookbook/src/app/showcase/form-field-showcase/form-field-showcase.component.ts
  libs/designsystem/form-field/src/input-counter/input-counter.component.spec.ts
  libs/designsystem/form-field/src/input-counter/input-counter.component.ts
  libs/designsystem/form-field/src/input/input.component.ts
  libs/designsystem/form-field/src/textarea/textarea.component.spec.ts
  libs/designsystem/form-field/src/textarea/textarea.component.ts
Labels: fix

#3902 Message/Empty State: encapsulate styles to not be overwritable on host element
  libs/designsystem/empty-state/src/empty-state.component.html
  libs/designsystem/empty-state/src/empty-state.component.scss
Labels: fix

#3907 Release v10.5.0
  libs/core/package.json
  libs/designsystem/package.json
  package-lock.json
Labels: ignore-for-release
