Repository kirbydesign/designsystem, pull requests merged in 2025-03, with the labels that each got.

#3846 Housekeeping: Update deprecated cache versions
  .github/actions/kirby-setup/action.yml
  .github/workflows/build.yml
Labels: ignore-for-release

#3851 Checkbox: update view when updating value with ng forms
  libs/designsystem/checkbox/src/checkbox.component.ts
Labels: fix

#3849 Formatting Pipes: show currency symbol
  libs/extensions/angular/localization/src/amount/amount-service-formatter.ts
  libs/extensions/angular/localization/src/amount/amount.service.spec.ts
  libs/extensions/angular/localization/src/amount/amount.service.ts
  libs/extensions/angular/localization/src/amount/amount.stories.ts
  libs/extensions/angular/localization/src/di-tokens.ts
  libs/extensions/angular/localization/src/formatting-pipes.mdx
Labels: breaking-change

#3853 Image Banner: toggle button mobile view, refactor and accessibility changes
  libs/designsystem/shared/src/translation/translation.interface.ts
  libs/designsystem/shared/src/translation/translations/da.ts
  libs/designsystem/shared/src/translation/translations/de.ts
  libs/designsystem/shared/src/translation/translations/en.ts
  libs/extensions/angular/image-banner/src/image-banner.component.html
  libs/extensions/angular/image-banner/src/image-banner.component.scss
  libs/extensions/angular/image-banner/src/image-banner.component.stories.ts
  libs/extensions/angular/image-banner/src/image-banner.component.ts
Labels: feature

#3867 Release Extensions v3.1.0
  libs/extensions/angular/package.json
  package-lock.json
Labels: ignore-for-release

#3877 Input: pin date-mask font-size to match value
  libs/designsystem/form-field/src/directives/date/date-input.directive.spec.ts
  libs/designsystem/form-field/src/input/input.component.scss
Labels: fix

#3865 Message State: Remove article from empty-state
  libs/designsystem/empty-state/src/empty-state.component.html
  libs/designsystem/empty-state/src/empty-state.component.scss
Labels: fix
