Repository kirbydesign/designsystem, pull requests merged in 2025-01, with the labels that each got.

#3755 Deps: Add fixed stencil version to peer dependencies
  libs/designsystem/package.json
  package-lock.json
Labels: ignore-for-release

#3750 Housekeeping: Migrate include-media scss built-in fuctions
  libs/core/src/scss/base/_include-media.scss
Labels: ignore-for-release

#3754 Housekeeping: Add link between interface and implementation when compiling ts for easy jump to implementation
  tsconfig.base.json
Labels: ignore-for-release

#3757 Form Field: adjust spacing between label and nested interactive
  libs/designsystem/form-field/src/form-field.component.scss
  libs/designsystem/form-field/src/form-field.component.spec.ts
Labels: fix

#3761 Icons: Add expense, income, notification-fill and signed-document
  libs/designsystem/icon/src/icons/svg/expense.svg
  libs/designsystem/icon/src/icons/svg/income.svg
  libs/designsystem/icon/src/icons/svg/notification-fill.svg
  libs/designsystem/icon/src/icons/svg/signed-document.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: feature

#3768 Icon: hide icons from assistive technology by default
  apps/cookbook/src/app/showcase/icon-showcase/icon-showcase.component.html
  libs/designsystem/icon/src/icon.component.ts
Labels: feature

#3778 Release v10.3.0
  libs/core/package.json
  libs/designsystem/package.json
  package-lock.json
Labels: ignore-for-release
