Repository kirbydesign/designsystem, pull requests merged in 2025-07, with the labels that each got.

#3987 Image Banner: removed duplicate button/anchor tag behavior
  libs/extensions/angular/image-banner/src/image-banner.component.html
  libs/extensions/angular/image-banner/src/image-banner.component.scss
  libs/extensions/angular/image-banner/src/image-banner.component.ts
Labels: fix

#3899 Page: added use of title properties for HTML document title updates
  apps/cookbook/src/app/examples/page-example/advanced/page-advanced-example.component.ts
  apps/cookbook/src/app/examples/page-example/advanced/page-custom-title-example.component.ts
  apps/cookbook/src/app/showcase/page-showcase/page-showcase.component.html
  libs/designsystem/page/src/page.component.spec.ts
  libs/designsystem/page/src/page.component.ts
Labels: fix

#3974 Accordion: allow heading markup in accordion title
  apps/cookbook/src/app/examples/accordion-example/accordion-example.component.html
  apps/cookbook/src/app/examples/accordion-example/accordion-example.component.ts
  apps/cookbook/src/app/examples/accordion-example/examples/heading-level.ts
  apps/cookbook/src/app/showcase/accordion-showcase/accordion-showcase.component.html
  apps/cookbook/src/app/showcase/accordion-showcase/accordion-showcase.component.scss
  apps/cookbook/src/app/showcase/accordion-showcase/accordion-showcase.component.ts
  libs/designsystem/accordion/src/accordion-item.component.html
  libs/designsystem/accordion/src/accordion-item.component.scss
  libs/designsystem/accordion/src/accordion-item.component.spec.ts
  libs/designsystem/accordion/src/accordion-item.component.ts
  libs/designsystem/accordion/src/accordion.directive.ts
Labels: feature

#3999 Segmented Control: Added optional aria label for segment item
  apps/cookbook/src/app/showcase/segmented-control-showcase/segmented-control-showcase.component.html
  apps/cookbook/src/app/showcase/segmented-control-showcase/segmented-control-showcase.component.ts
  libs/designsystem/src/lib/components/segmented-control/segment-item.ts
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.html
  libs/designsystem/src/lib/components/segmented-control/segmented-control.component.spec.ts
Labels: enhancement, accessibility

#3995 Image banner: allow custom heading markup for image banner title
  libs/extensions/angular/image-banner/src/image-banner.component.html
  libs/extensions/angular/image-banner/src/image-banner.component.scss
  libs/extensions/angular/image-banner/src/image-banner.component.stories.ts
Labels: fix

#4004 Test: Await title change before expecting new title in router outlet test
  libs/designsystem/router-outlet/src/router-outlet.integration.spec.ts
Labels: ignore-for-release

#4009 Deps: Support Angular 20
  apps/cookbook/package.json
  eslint.config.mjs
  libs/angular/package.json
  libs/core/src/scss/_global-styles.scss
  libs/core/src/scss/base/_link.scss
  libs/designsystem/.storybook/main.ts
  libs/designsystem/.storybook/preview.ts
  libs/designsystem/.storybook/tsconfig.json
  libs/designsystem/data-table/src/data-table.stories.ts
  libs/designsystem/data-table/src/sortable/sortable.component.spec.ts
  libs/designsystem/dropdown/src/dropdown.component.stories.ts
  libs/designsystem/eslint.config.mjs
  libs/designsystem/form-field/src/form-field.component.ts
  libs/designsystem/item-sliding/src/item-sliding.component.spec.ts
  libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts
  libs/designsystem/modal/src/modal/alert/alert.component.spec.ts
  libs/designsystem/package.json
  libs/designsystem/project.json
  libs/designsystem/radio/src/radio-group/radio-group.component.spec.ts
  libs/extensions/angular/.storybook/main.ts
  libs/extensions/angular/.storybook/preview.ts
  libs/extensions/angular/.storybook/tsconfig.json
  libs/extensions/angular/docs/Introduction.mdx
  libs/extensions/angular/jest.config.ts
  libs/extensions/angular/localization/src/formatting-pipes.mdx
  libs/extensions/angular/package.json
  libs/extensions/angular/project.json
  libs/extensions/angular/tsconfig.spec.json
  nx.json
  package-lock.json
  package.json
  tools/sass-to-ts/package.json
  tools/storybook-config/shared-config.ts
  tsconfig.base.json
Labels: feature

#4014 Docs: remove random string generation from slides example
  apps/cookbook/src/app/examples/slides-example/examples/height.ts
Labels: ignore-for-release
