Repository kirbydesign/designsystem, pull requests merged in 2025-02, with the labels that each got.

#3759 Housekeeping/fix dropdown custom template example in cookbook
  apps/cookbook/src/app/examples/dropdown-example/examples/custom-item-template.ts
  libs/designsystem/dropdown/src/dropdown.module.ts
Labels: ignore-for-release

#3739 Toggle: fix missing space between toggle and its slotted content when slot=end in item
  apps/cookbook/src/app/examples/item-example/examples/settings/settings.ts
  libs/designsystem/item/src/item.component.stories.ts
  libs/designsystem/toggle/src/toggle.component.html
  libs/designsystem/toggle/src/toggle.component.scss
  libs/designsystem/toggle/src/toggle.component.ts
Labels: fix

#3781 Remove unneeded comments
  libs/designsystem/divider/src/divider.component.spec.ts
  libs/designsystem/form-field/src/input/input.component.ts
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: ignore-for-release

#3735 Localization: Add formatting pipes
  libs/extensions/angular/.storybook/preview.ts
  libs/extensions/angular/localization/ng-package.json
  libs/extensions/angular/localization/src/account-number/account-number-service-formatter.ts
  libs/extensions/angular/localization/src/account-number/account-number.model.ts
  libs/extensions/angular/localization/src/account-number/account-number.pipe.spec.ts
  libs/extensions/angular/localization/src/account-number/account-number.pipe.ts
  libs/extensions/angular/localization/src/account-number/account-number.stories.ts
  libs/extensions/angular/localization/src/account-number/index.ts
  libs/extensions/angular/localization/src/amount/amount-service-formatter.ts
  libs/extensions/angular/localization/src/amount/amount.model.ts
  libs/extensions/angular/localization/src/amount/amount.pipe.spec.ts
  libs/extensions/angular/localization/src/amount/amount.pipe.ts
  libs/extensions/angular/localization/src/amount/amount.service.spec.ts
  libs/extensions/angular/localization/src/amount/amount.service.ts
  libs/extensions/angular/localization/src/amount/amount.stories.ts
  libs/extensions/angular/localization/src/amount/index.ts
  libs/extensions/angular/localization/src/date-time/abstract-timezone-compensating.pipe.ts
  libs/extensions/angular/localization/src/date-time/date-formats.ts
  libs/extensions/angular/localization/src/date-time/date-only/date-only.pipe.spec.ts
  libs/extensions/angular/localization/src/date-time/date-only/date-only.pipe.ts
  libs/extensions/angular/localization/src/date-time/date-only/date-only.stories.ts
  libs/extensions/angular/localization/src/date-time/index.ts
  libs/extensions/angular/localization/src/date-time/time-only/time-only.pipe.spec.ts
  libs/extensions/angular/localization/src/date-time/time-only/time-only.pipe.ts
  libs/extensions/angular/localization/src/date-time/time-only/time-only.stories.ts
  libs/extensions/angular/localization/src/date-time/time-or-date/time-or-date.pipe.spec.ts
  libs/extensions/angular/localization/src/date-time/time-or-date/time-or-date.pipe.ts
  libs/extensions/angular/localization/src/date-time/time-or-date/time-or-date.stories.ts
  libs/extensions/angular/localization/src/di-tokens.ts
  libs/extensions/angular/localization/src/formatting-pipes.mdx
  libs/extensions/angular/localization/src/index.ts
  libs/extensions/angular/localization/src/number/format-number.pipe.ts
  libs/extensions/angular/localization/src/number/format-number.service.spec.ts
  libs/extensions/angular/localization/src/number/format-number.service.ts
  libs/extensions/angular/localization/src/number/format-number.stories.ts
  libs/extensions/angular/localization/src/number/index.ts
  libs/extensions/angular/localization/src/phone-number/index.ts
  libs/extensions/angular/localization/src/phone-number/phone-number.pipe.ts
  libs/extensions/angular/localization/src/phone-number/phone-number.service.spec.ts
  libs/extensions/angular/localization/src/phone-number/phone-number.service.ts
  libs/extensions/angular/localization/src/phone-number/phone-number.stories.ts
  libs/extensions/angular/localization/src/phone-number/phone-number.ts
  libs/extensions/angular/package.json
  package-lock.json
  tsconfig.base.json
Labels: enhancement, 3rd party development

#3747 Skeleton Loader: Add new skeleton loader component
  libs/designsystem/tsconfig.spec.json
  libs/extensions/angular/skeleton-loader/ng-package.json
  libs/extensions/angular/skeleton-loader/src/index.ts
  libs/extensions/angular/skeleton-loader/src/skeleton-loader.component.html
  libs/extensions/angular/skeleton-loader/src/skeleton-loader.component.scss
  libs/extensions/angular/skeleton-loader/src/skeleton-loader.component.spec.ts
  libs/extensions/angular/skeleton-loader/src/skeleton-loader.component.stories.ts
  libs/extensions/angular/skeleton-loader/src/skeleton-loader.component.ts
  package-lock.json
  package.json
  tsconfig.base.json
Labels: feature

#3746 Form field: announce error text when nested interactive is focussed
  libs/designsystem/dropdown/src/dropdown.module.ts
  libs/designsystem/form-field/src/form-field.component.html
  libs/designsystem/form-field/src/form-field.component.spec.ts
  libs/designsystem/form-field/src/form-field.component.ts
  libs/designsystem/form-field/src/input/input.component.ts
  libs/designsystem/form-field/src/textarea/textarea.component.ts
  libs/designsystem/radio/src/radio-group/radio-group.component.html
  libs/designsystem/radio/src/radio-group/radio-group.component.ts
  libs/designsystem/types/src/form-field-control.ts
  libs/designsystem/types/src/public_api.ts
Labels: feature

#3800 Housekeeping: remove redundant git add in lint-staged config
  .lintstagedrc
Labels: ignore-for-release

#3789 Formatting Pipes: Make amount pipes amountServiceConfiguration optional
  libs/extensions/angular/localization/src/amount/amount-service-formatter.ts
  libs/extensions/angular/localization/src/amount/amount.pipe.ts
  libs/extensions/angular/localization/src/amount/amount.service.ts
  libs/extensions/angular/localization/src/amount/amount.stories.ts
  libs/extensions/angular/localization/src/formatting-pipes.mdx
Labels: breaking-change

#3797 Docs: Re-introduce examples-routing.module to fix lazy loaded route modals
  apps/cookbook/src/app/app.routes.ts
  apps/cookbook/src/app/examples/examples-routing.module.ts
Labels: housekeeping, ignore-for-release
