Repository kirbydesign/designsystem, pull requests merged in 2025-08, with the labels that each got.

#4016 Icon: top-up icon uploaded
  libs/designsystem/icon/src/icons/svg/top-up.svg
  libs/designsystem/icon/src/kirby-icon-settings.ts
Labels: feature

#4029 Empty State: Use h2 element for title when within modal
  libs/designsystem/empty-state/src/empty-state.component.html
  libs/designsystem/empty-state/src/empty-state.component.spec.ts
  libs/designsystem/empty-state/src/empty-state.component.ts
  libs/designsystem/modal/src/modal/services/alert.helper.spec.ts
Labels: fix

#4031 Decimal Mask: Trigger blur event for reactive forms
  libs/designsystem/form-field/src/directives/decimal-mask/decimal-mask.directive.spec.ts
  libs/designsystem/form-field/src/directives/decimal-mask/decimal-mask.directive.ts
Labels: fix

#4032 Release v11.1.1 (bump stencil)
  libs/core/package.json
  libs/designsystem/package.json
  package-lock.json
Labels: dependencies
